/**
 * Auto-generate `src/components/${component}/index.ts` for every component
 * listed in `registry-manifest.json`.
 *
 * Generated files are gitignored (derived artifacts). Run during prebuild so
 * vite build + typecheck + lint can resolve `./components/${name}` imports.
 *
 * The barrel content is generated by the shared `buildComponentIndexContent`
 * function (from brutx-shared-vue), which is also used by the registry build
 * to produce identical content inline.
 *
 * Usage: tsx scripts/generate-component-index.ts
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildComponentIndexContent } from 'brutx-shared-vue/scan'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const UI_SRC_DIR = path.resolve(__dirname, '..', 'src')
const MANIFEST_PATH = path.resolve(__dirname, '..', 'registry-manifest.json')

interface ComponentFileManifest {
    files: string[]
    composables: string[]
    directives: string[]
    lib: string[]
}

type RegistryManifest = Record<string, ComponentFileManifest>

function main(): void {
    if (!fs.existsSync(MANIFEST_PATH)) {
        throw new Error(
            `registry-manifest.json not found at ${MANIFEST_PATH}\n` +
            'Run `pnpm prebuild:scan` first.',
        )
    }

    const manifest: RegistryManifest = JSON.parse(
        fs.readFileSync(MANIFEST_PATH, 'utf-8'),
    )

    const componentNames = Object.keys(manifest).sort()
    console.log(`🔧 Generating index.ts for ${componentNames.length} components...`)

    let generated = 0
    let skipped = 0
    for (const name of componentNames) {
        const componentDir = path.join(UI_SRC_DIR, 'components', name)
        if (!fs.existsSync(componentDir)) {
            console.warn(`  ! skipping "${name}": directory not found`)
            skipped++
            continue
        }

        const indexPath = path.join(componentDir, 'index.ts')
        const content = buildComponentIndexContent(manifest[name].files)
        fs.writeFileSync(indexPath, content, 'utf-8')
        generated++
    }

    console.log(`✓ Generated ${generated} index.ts files (${skipped} skipped)`)
}

main()
