/**
 * Auto-generate `src/components/${component}/index.ts` for every component
 * listed in `registry-manifest.json`.
 *
 * Generated files are gitignored (derived artifacts). Run during prebuild so
 * vite build + typecheck + lint can resolve `./components/${name}` imports.
 *
 * Pattern:
 *   - `.vue` files → `export { default as PascalCase } from './File.vue'`
 *   - `.ts` files  → `export * from './file'` (variants, types, keys, contexts)
 *   - `.css` files → skipped (side-effect imports handled by vite)
 *   - `index.ts`   → skipped (the file being generated)
 *   - test files   → skipped (already filtered by scanner)
 *
 * Usage: tsx scripts/generate-component-index.ts
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const UI_SRC_DIR = path.resolve(__dirname, '..', 'src')
const MANIFEST_PATH = path.resolve(__dirname, '..', 'registry-manifest.json')

interface ComponentFileManifest {
    files: string[]
    composables: string[]
    directives: string[]
    lib: string[]
}

type RegistryManifest = Record<string, ComponentFileManifest>

const AUTO_GEN_HEADER = `/**
 * AUTO-GENERATED by scripts/generate-component-index.ts — DO NOT EDIT.
 * Regenerated on every \`pnpm prebuild:scan\` run.
 * To add public exports, edit the underlying .vue/.ts file (it will be
 * picked up automatically on the next prebuild).
 */
`

function vueFileNameToExportName(fileName: string): string {
    // Button.vue → Button; AccordionContent.vue → AccordionContent
    return fileName.replace(/\.vue$/, '')
}

function tsFileNameToModuleSpec(fileName: string): string {
    // accordion-variants.ts → './accordion-variants'
    return `./${fileName.replace(/\.ts$/, '')}`
}

function buildComponentIndex(manifest: ComponentFileManifest): string {
    const lines: string[] = [AUTO_GEN_HEADER]

    const sortedFiles = [...manifest.files].sort()
    for (const file of sortedFiles) {
        if (file === 'index.ts') continue
        if (file.endsWith('.test.ts') || file.endsWith('.spec.ts')) continue
        if (file.endsWith('.browser.test.ts')) continue

        if (file.endsWith('.vue')) {
            const exportName = vueFileNameToExportName(file)
            lines.push(`export { default as ${exportName} } from './${file}'`)
            // SFC <script setup> may export types/interfaces (e.g. CalendarEvent,
            // SelectProps). `export type *` re-exports them without runtime cost.
            lines.push(`export type * from './${file}'`)
        } else if (file.endsWith('.ts')) {
            lines.push(`export * from '${tsFileNameToModuleSpec(file)}'`)
        }
        // .css files intentionally skipped
    }

    return lines.join('\n') + '\n'
}

function main(): void {
    if (!fs.existsSync(MANIFEST_PATH)) {
        throw new Error(
            `registry-manifest.json not found at ${MANIFEST_PATH}\n` +
            'Run `pnpm prebuild:scan` first.',
        )
    }

    const manifest: RegistryManifest = JSON.parse(
        fs.readFileSync(MANIFEST_PATH, 'utf-8'),
    )

    const componentNames = Object.keys(manifest).sort()
    console.log(`🔧 Generating index.ts for ${componentNames.length} components...`)

    let generated = 0
    let skipped = 0
    for (const name of componentNames) {
        const componentDir = path.join(UI_SRC_DIR, 'components', name)
        if (!fs.existsSync(componentDir)) {
            console.warn(`  ! skipping "${name}": directory not found`)
            skipped++
            continue
        }

        const indexPath = path.join(componentDir, 'index.ts')
        const content = buildComponentIndex(manifest[name])
        fs.writeFileSync(indexPath, content, 'utf-8')
        generated++
    }

    console.log(`✓ Generated ${generated} index.ts files (${skipped} skipped)`)
}

main()
