/**
 * Auto-generate `src/components/${component}/index.ts` for every component
 * listed in the explicit UI API contract.
 *
 * Generated files are gitignored (derived artifacts). Run during prebuild so
 * vite build + typecheck + lint can resolve `./components/${name}` imports.
 *
 * The barrel content is generated by the shared `buildComponentIndexContent`
 * function (from brutx-shared-vue) from a named export projection.
 *
 * Usage: tsx scripts/generate-component-index.ts
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
    compareGeneratedOutputs,
    type GeneratedOutput,
    hasMissingGeneratedOutputs,
    withGenerateLock,
    writeGeneratedOutputs,
} from 'brutx-shared-vue/generation'
import { buildComponentIndexContent } from 'brutx-shared-vue/scan'
import { API_CONTRACT, projectComponentExports } from '../api-contract.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const PACKAGE_ROOT = path.resolve(__dirname, '..')

export function collectComponentIndexOutputs(packageRoot?: string): GeneratedOutput[]
export function collectComponentIndexOutputs(_manifest: unknown, packageRoot?: string): GeneratedOutput[]
export function collectComponentIndexOutputs(
    manifestOrPackageRoot: unknown = PACKAGE_ROOT,
    explicitPackageRoot?: string,
): GeneratedOutput[] {
    const packageRoot = typeof manifestOrPackageRoot === 'string'
        ? manifestOrPackageRoot
        : explicitPackageRoot ?? PACKAGE_ROOT
    const uiSrcDir = path.resolve(packageRoot, 'src')
    const componentNames = API_CONTRACT.entries
        .filter((entry) => entry.kind === 'component')
        .map((entry) => entry.subpath.slice(2))
        .sort()
    const outputs: GeneratedOutput[] = []
    for (const name of componentNames) {
        const componentDir = path.join(uiSrcDir, 'components', name)
        if (!fs.existsSync(componentDir)) {
            throw new Error(`API contract component directory not found: ${name}`)
        }
        outputs.push({
            relativePath: path.posix.join('src', 'components', name, 'index.ts'),
            content: buildComponentIndexContent(projectComponentExports(name)),
            allowMissing: true,
        })
    }
    return outputs
}

function runStandalone(): void {
    const isCheckMode = process.argv.includes('--check')
    const isVerbose = process.argv.includes('--verbose') || process.argv.includes('-v') || process.env.BRUTX_VERBOSE === '1'
    const outputs = collectComponentIndexOutputs(PACKAGE_ROOT)
    const differences = compareGeneratedOutputs(PACKAGE_ROOT, outputs)
    const hasMissingOutputs = hasMissingGeneratedOutputs(PACKAGE_ROOT, outputs)

    if (isCheckMode) {
        if (differences.length === 0) {
            console.log(`✓ Component index files up-to-date (${outputs.length})`)
            return
        }
        console.error('✗ component index 生成内容与磁盘不一致')
        for (const difference of differences) console.error(`  - ${difference.relativePath} (${difference.kind})`)
        throw new Error('UI component index 生成检查失败')
    }

    if (differences.length > 0 || hasMissingOutputs) writeGeneratedOutputs(PACKAGE_ROOT, outputs)

    if (isVerbose) console.log(`✓ Generated ${outputs.length} component index files`)
}

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
    const runPromise = process.argv.includes('--check')
        ? Promise.resolve().then(runStandalone)
        : withGenerateLock(
            { packageName: 'brutx-ui-vue', cacheDir: path.resolve(PACKAGE_ROOT, 'node_modules', '.cache') },
            runStandalone,
        )
    runPromise.catch((err) => {
        console.error(err)
        process.exit(1)
    })
}
