import type { ApiContent, ApiSemantic } from '../api-types'

const actionHtmlProps = {
    disabled: { zh: '禁用原生按钮，使其无法通过常规用户交互激活；使用自定义根元素时由该元素实现禁用行为。', en: 'Disables normal user activation of a native button. A custom root element must implement its own disabled behavior.' },
    dir: { zh: '设置根元素及其文本的书写方向，例如 ltr、rtl 或 auto。', en: 'Sets the text direction of the root element, such as ltr, rtl, or auto.' },
    type: {
        zh: '设置原生按钮的行为：普通按钮、提交表单或重置表单。',
        en: 'Selects native button behavior: a regular button, form submission, or form reset.',
        fallback: {
            'zh-CN': '未提供且 Reka 原语的 as 为 button 时，底层 DialogClose 使用 type="button"。',
            en: 'When omitted and the Reka primitive uses as="button", the underlying DialogClose supplies type="button".',
        },
    },
    form: { zh: '通过表单元素的 ID 指定按钮所属表单，可以关联 DOM 祖先之外的表单。', en: 'Associates the button with a form by its element ID, including a form outside its DOM ancestors.' },
    value: { zh: '按钮作为提交者时，与 name 一同写入表单数据的值；按钮可见文字由默认插槽提供。', en: 'The value included with name in form data when this button is the submitter. Visible button text comes from the default slot.' },
    id: { zh: '根元素的 DOM ID，用于标签关联、选择器和页面定位。', en: 'The root element’s DOM ID, used by label references, selectors, and fragment links.' },
    autofocus: { zh: '向浏览器请求自动聚焦；对话框打开时仍会执行 Reka 的焦点管理。', en: 'Requests browser autofocus. Reka still performs its focus management when the dialog opens.' },
    formaction: { zh: '此按钮提交所属表单时使用的目标 URL，覆盖表单的 action。', en: 'The destination URL used when this button submits its form, overriding the form action.' },
    formenctype: { zh: '此按钮提交表单时采用的数据编码方式，覆盖表单的 enctype。', en: 'The data encoding used when this button submits its form, overriding the form enctype.' },
    formmethod: { zh: '此按钮提交表单时采用的方法，覆盖表单的 method。', en: 'The submission method used by this button, overriding the form method.' },
    formnovalidate: { zh: '此按钮提交表单时跳过浏览器的表单约束校验。', en: 'Skips browser constraint validation when this button submits its form.' },
    formtarget: { zh: '指定此按钮提交表单后用于显示响应的浏览上下文，覆盖表单的 target。', en: 'Selects the browsing context that displays this button’s form response, overriding the form target.' },
    name: { zh: '按钮作为提交者时写入表单数据的字段名，与 value 配合使用。', en: 'The field name included in form data with value when this button is the submitter.' },
    innerHTML: { zh: '将 HTML 字符串写入根元素的内容区域；该内容替代默认插槽渲染的子节点。', en: 'Writes an HTML string into the root element, replacing the children rendered by its default slot.' },
    accesskey: { zh: '为根元素提供浏览器访问快捷键提示，实际组合键由浏览器和操作系统决定。', en: 'Provides an access-key hint for the root element; the browser and operating system determine the key combination.' },
    contenteditable: { zh: '设置根元素内容是否可编辑；plaintext-only 表示仅编辑纯文本，inherit 表示继承编辑状态。', en: 'Controls whether root content is editable; plaintext-only allows plain-text editing, while inherit inherits the editing state.' },
    contextmenu: { zh: '旧式 HTML 上下文菜单关联属性，值为 menu 元素 ID；不负责创建或打开 BrutxUI 菜单。', en: 'A legacy HTML context-menu association containing a menu element ID; it does not create or open a BrutxUI menu.' },
    draggable: { zh: '设置根元素是否可作为浏览器原生拖放的拖动源。', en: 'Controls whether the root element can be a source for native browser drag and drop.' },
    enterkeyhint: { zh: '为可编辑根元素的虚拟键盘提供回车键标签或图标提示。', en: 'Suggests the virtual keyboard’s Enter-key label or icon for an editable root element.' },
    enterKeyHint: { zh: 'Vue 保留的 enterkeyhint 驼峰别名，用于虚拟键盘回车键提示；该别名已弃用，使用 enterkeyhint。', en: 'Vue’s deprecated camel-case alias for the virtual keyboard Enter-key hint; use enterkeyhint.' },
    hidden: { zh: '控制根元素的 HTML 隐藏状态；until-found 允许支持该值的浏览器通过页内查找等操作揭示内容。', en: 'Controls the root element’s HTML hidden state; until-found allows supporting browsers to reveal it through features such as find-in-page.' },
    inert: { zh: '使根元素及其平面树后代进入惰性状态，无法聚焦或进行常规用户交互。', en: 'Makes the root and its flat-tree descendants inert, preventing focus and normal user interaction.' },
    lang: { zh: '标记根元素内容的语言，供读屏发音和浏览器文本处理使用。', en: 'Identifies the language of the root content for screen-reader pronunciation and browser text processing.' },
    placeholder: { zh: '传递输入占位提示；仅对支持该属性的输入根元素生效，普通 button 不显示占位文本。', en: 'Passes an input placeholder to a supporting input root; a regular button does not display placeholder text.' },
    spellcheck: { zh: '为可编辑内容设置浏览器拼写检查提示。', en: 'Controls the browser’s spell-checking hint for editable content.' },
    tabindex: { zh: '设置根元素的焦点顺序；0 使用文档顺序，-1 允许程序化聚焦并移出顺序键盘导航。', en: 'Sets root focus order: 0 uses document order, while -1 allows programmatic focus outside sequential keyboard navigation.' },
    title: { zh: '为根元素提供浏览器原生的补充提示文本。', en: 'Provides supplementary text through the browser’s native title behavior.' },
    translate: { zh: '指定浏览器或翻译工具是否应翻译根元素的可翻译文本和属性。', en: 'Indicates whether translation tools should translate the root element’s translatable text and attributes.' },
    radiogroup: { zh: '旧式 HTML radio command 的互斥组名称；不会为确认按钮建立单选组行为。', en: 'The group name for legacy HTML radio commands; it does not give the action button radio-group behavior.' },
    role: { zh: '设置根元素向辅助技术公开的角色，须与实际元素和交互行为相符。', en: 'Sets the root’s role for assistive technology; it must match the rendered element and its interaction behavior.' },
    about: { zh: 'RDFa 元数据所描述的主体资源标识。', en: 'Identifies the subject resource described by RDFa metadata.' },
    datatype: { zh: '指定 RDFa 字面量值的数据类型。', en: 'Specifies the datatype of an RDFa literal value.' },
    inlist: { zh: '将同元素上 RDFa 关系的对象加入对应谓词的列表；由属性是否存在决定，值本身被忽略。', en: 'Adds the RDFa relationship object to its predicate’s list; presence matters and the attribute value is ignored.' },
    prefix: { zh: '声明 RDFa 前缀与 IRI 的映射，供元数据中的缩写标识使用。', en: 'Declares RDFa prefix-to-IRI mappings for abbreviated metadata identifiers.' },
    property: { zh: '声明 RDFa 主体与资源或字面量之间的属性关系。', en: 'Declares RDFa properties relating a subject to a resource or literal.' },
    resource: { zh: '指定 RDFa 关系中使用的资源标识。', en: 'Supplies a resource identifier used in an RDFa relationship.' },
    typeof: { zh: '声明 RDFa 所描述资源所属的类型。', en: 'Declares the types of the resource described by RDFa.' },
    vocab: { zh: '指定 RDFa 术语使用的默认词汇表 IRI。', en: 'Sets the default vocabulary IRI used for RDFa terms.' },
    autocapitalize: { zh: '为可编辑内容提供自动大写策略提示，例如句首、单词首字母或全部字符。', en: 'Suggests automatic capitalization for editable content, such as sentences, words, or all characters.' },
    autocorrect: { zh: '为支持自动纠错的可编辑根元素提供开关提示。', en: 'Provides an autocorrection hint for an editable root that supports it.' },
    autosave: { zh: 'Safari 搜索输入框扩展属性，用作保存搜索历史的名称；普通 button 不保存搜索记录。', en: 'A Safari search-input extension naming stored search history; a regular button does not save searches.' },
    color: { zh: '传递旧式 HTML color 呈现属性；确认按钮的配色由 variant 和 CSS 类控制。', en: 'Passes the legacy HTML color presentation attribute; the action button’s colors are controlled by variant and CSS classes.' },
    itemprop: { zh: '声明根元素在 HTML 微数据中提供的属性名称。', en: 'Names the properties supplied by the root element in HTML microdata.' },
    itemscope: { zh: '为根元素创建 HTML 微数据项目的作用域。', en: 'Creates an HTML microdata item scope on the root element.' },
    itemtype: { zh: '为 itemscope 创建的微数据项目指定词汇类型 URL。', en: 'Specifies vocabulary type URLs for the microdata item created by itemscope.' },
    itemid: { zh: '为微数据项目提供全局标识，需与 itemscope 和 itemtype 配合。', en: 'Provides a global identifier for a microdata item, together with itemscope and itemtype.' },
    itemref: { zh: '引用作用域之外提供微数据属性的元素 ID，多个 ID 以空格分隔。', en: 'Lists space-separated IDs of elements outside the scope that contribute microdata properties.' },
    results: { zh: 'Safari 搜索输入框扩展属性，设置搜索历史菜单中的最大条目数；普通 button 不显示该菜单。', en: 'A Safari search-input extension limiting search-history menu entries; a regular button has no such menu.' },
    security: { zh: '旧式 Internet Explorer iframe 安全区域属性；确认按钮不使用此属性实现安全策略。', en: 'A legacy Internet Explorer iframe security-zone attribute; the action button does not use it to implement a security policy.' },
    unselectable: { zh: '旧式浏览器的选择控制属性，on 阻止从该元素开始选择文本，off 允许选择。', en: 'A legacy selection attribute: on prevents starting text selection on the element, while off allows it.' },
    inputmode: { zh: '提示可编辑根元素需要的虚拟键盘布局，例如 numeric 或 email；不执行输入校验。', en: 'Suggests a virtual keyboard layout for an editable root, such as numeric or email; it does not validate input.' },
    is: { zh: '声明标准 HTML 根元素对应的已注册定制内置元素名称，实际支持取决于浏览器和渲染方式。', en: 'Names a registered customized built-in element for the HTML root; support depends on the browser and rendering path.' },
    exportparts: { zh: '将 Shadow DOM 内部的 part 名称映射并暴露给外层的 ::part 选择器。', en: 'Maps and exposes names of internal shadow parts to outer ::part selectors.' },
    part: { zh: '声明根元素在 Shadow DOM 中的 part 名称，供外部通过 ::part 定制样式。', en: 'Names the root element’s shadow parts for external styling through ::part.' },
} satisfies Record<string, ApiSemantic>

const actionAriaProps = {
    'aria-activedescendant': { zh: '引用复合控件中当前活动子项的 ID；DOM 焦点保留在控件根元素。', en: 'References the active item in a composite widget while DOM focus stays on the widget root.' },
    'aria-atomic': { zh: '指定实时区域变化时，辅助技术朗读整个区域还是仅朗读变化部分。', en: 'Indicates whether a live-region change is announced as the whole region or only its changed parts.' },
    'aria-autocomplete': { zh: '描述文本输入控件的自动补全形式：行内、列表、两者兼有或不提供。', en: 'Describes text-input completion as inline, list-based, both, or absent.' },
    'aria-busy': { zh: '标记区域正在更新，提示辅助技术等待更新完成再呈现变化。', en: 'Marks a region as updating so assistive technology can defer presenting its changes.' },
    'aria-checked': { zh: '描述复选框、单选项等可勾选控件的状态；mixed 用于支持部分选中的角色。', en: 'Describes the checked state of checkable controls; mixed represents partial selection for roles that support it.' },
    'aria-colcount': { zh: '提供表格、网格或树形网格的总列数，包括未呈现在 DOM 中的列。', en: 'Provides the total column count of a table, grid, or treegrid, including columns absent from the DOM.' },
    'aria-colindex': { zh: '提供表格或网格中元素从 1 开始的列位置。', en: 'Provides an element’s one-based column position in a table or grid.' },
    'aria-colspan': { zh: '提供表格或网格单元格横跨的列数。', en: 'Provides the number of columns spanned by a table or grid cell.' },
    'aria-controls': { zh: '引用当前控件所控制内容的元素 ID，多个 ID 以空格分隔。', en: 'Lists space-separated IDs of elements whose content or presence this control manages.' },
    'aria-current': { zh: '标记关联项目中的当前项，并可说明当前页、步骤、位置、日期或时间。', en: 'Identifies the current item in a related set, optionally as a page, step, location, date, or time.' },
    'aria-describedby': { zh: '引用为根元素提供补充描述的元素 ID，多个 ID 以空格分隔。', en: 'Lists space-separated IDs of elements that provide a supplementary description for the root.' },
    'aria-details': { zh: '引用提供可进一步浏览的结构化详细说明的元素。', en: 'References an element containing structured details that users can explore further.' },
    'aria-disabled': { zh: '向辅助技术声明控件不可操作；此属性本身不阻止点击或关闭对话框。', en: 'Communicates that the control is unavailable; this attribute alone does not prevent clicks or dialog closure.' },
    'aria-dropeffect': { zh: '已弃用的拖放语义，描述在目标上放下对象后可执行的操作。', en: 'Deprecated drag-and-drop semantics describing operations available when an object is dropped on the target.' },
    'aria-errormessage': { zh: '引用当前错误消息的元素 ID，配合 aria-invalid 表达无效状态。', en: 'References the current error-message element, together with aria-invalid to express an invalid state.' },
    'aria-expanded': { zh: '描述控件自身或其控制的内容是否展开；实际展开行为由业务处理。', en: 'Describes whether the control or its controlled content is expanded; application logic manages expansion.' },
    'aria-flowto': { zh: '引用可选阅读顺序中的后续元素，供辅助技术在用户选择时采用。', en: 'References subsequent elements in an alternative reading order that assistive technology can offer to users.' },
    'aria-grabbed': { zh: '已弃用的拖放状态，表示元素是否被抓取用于拖动。', en: 'A deprecated drag-and-drop state indicating whether the element is grabbed for dragging.' },
    'aria-haspopup': { zh: '声明控件可触发的交互式弹出内容类型，例如 menu 或 dialog；不自动创建弹层。', en: 'Declares the kind of interactive popup the control can open, such as menu or dialog; it does not create a popup.' },
    'aria-hidden': { zh: '控制元素及其后代是否从无障碍树中隐藏；不会改变视觉显示或键盘焦点。', en: 'Controls whether the element and descendants are hidden from the accessibility tree, without changing visual display or keyboard focus.' },
    'aria-invalid': { zh: '描述输入值是否无效，或存在语法、拼写错误。', en: 'Describes invalid input, including grammar or spelling errors.' },
    'aria-keyshortcuts': { zh: '公布业务已实现的键盘快捷键；此属性不会注册键盘监听器。', en: 'Advertises keyboard shortcuts already implemented by the application; it does not register key handlers.' },
    'aria-label': { zh: '直接提供根元素的无障碍名称，例如仅图标确认按钮的操作名称。', en: 'Provides the root’s accessible name directly, such as the action name of an icon-only confirmation button.' },
    'aria-labelledby': { zh: '引用提供根元素无障碍名称的元素 ID，多个 ID 以空格分隔。', en: 'Lists space-separated IDs of elements that supply the root’s accessible name.' },
    'aria-level': { zh: '提供标题、树项等层级结构成员从 1 开始的层级。', en: 'Provides the one-based level of a hierarchical item, such as a heading or tree item.' },
    'aria-live': { zh: '设置实时区域更新的通知优先级：关闭自动通知、礼貌通知或立即通知。', en: 'Sets live-region announcement priority: off, polite, or assertive.' },
    'aria-modal': { zh: '声明适用的对话框角色为模态；仅为语义声明，焦点限制由对话框原语实现。', en: 'Declares a supported dialog role as modal; dialog primitives implement the actual focus containment.' },
    'aria-multiline': { zh: '描述文本框是否接受多行输入。', en: 'Describes whether a textbox accepts multiple lines of input.' },
    'aria-multiselectable': { zh: '描述可选择集合是否允许同时选中多个子项。', en: 'Describes whether a selectable collection allows multiple selected items.' },
    'aria-orientation': { zh: '描述控件采用水平还是垂直方向布局。', en: 'Describes whether a widget uses horizontal or vertical orientation.' },
    'aria-owns': { zh: '通过元素 ID 建立 DOM 层级未表达的无障碍父子关系。', en: 'Uses element IDs to establish accessibility ownership not expressed by the DOM hierarchy.' },
    'aria-placeholder': { zh: '为无值的输入控件提供预期内容或格式提示；不替代控件名称。', en: 'Provides an expected-value or format hint for an empty input control; it does not replace the control’s name.' },
    'aria-posinset': { zh: '描述列表项或树项在当前集合中从 1 开始的位置。', en: 'Describes a list or tree item’s one-based position in its set.' },
    'aria-pressed': { zh: '描述切换按钮的按下状态；mixed 表示混合状态，状态切换由业务管理。', en: 'Describes a toggle button’s pressed state; mixed indicates a mixed state, and application logic manages changes.' },
    'aria-readonly': { zh: '声明支持该状态的控件可操作但其值不能编辑。', en: 'Declares that a supporting widget remains operable while its value cannot be edited.' },
    'aria-relevant': { zh: '指定实时区域中哪些变化需要通知，包括新增、移除和文本变化。', en: 'Selects which live-region changes warrant announcements, including additions, removals, and text changes.' },
    'aria-required': { zh: '声明输入控件必须提供值；表单实际校验由原生约束或业务逻辑执行。', en: 'Declares that an input control requires a value; native constraints or application logic perform validation.' },
    'aria-roledescription': { zh: '为现有角色提供面向用户的本地化说明。', en: 'Provides a localized, user-facing description of the element’s existing role.' },
    'aria-rowcount': { zh: '提供表格、网格或树形网格的总行数，包括未呈现在 DOM 中的行。', en: 'Provides the total row count of a table, grid, or treegrid, including rows absent from the DOM.' },
    'aria-rowindex': { zh: '提供表格或网格中元素从 1 开始的行位置。', en: 'Provides an element’s one-based row position in a table or grid.' },
    'aria-rowspan': { zh: '提供表格或网格单元格纵跨的行数。', en: 'Provides the number of rows spanned by a table or grid cell.' },
    'aria-selected': { zh: '描述选项、标签页、网格行等支持角色的选中状态。', en: 'Describes selection for supporting roles such as options, tabs, and grid rows.' },
    'aria-setsize': { zh: '提供列表项或树项所属集合的总项目数。', en: 'Provides the total item count in the set containing a list or tree item.' },
    'aria-sort': { zh: '描述表格或网格表头对应数据的排序方向。', en: 'Describes the sort direction of data associated with a table or grid header.' },
    'aria-valuemax': { zh: '提供范围控件允许的最大值。', en: 'Provides the maximum permitted value of a range widget.' },
    'aria-valuemin': { zh: '提供范围控件允许的最小值。', en: 'Provides the minimum permitted value of a range widget.' },
    'aria-valuenow': { zh: '提供范围控件当前的数值。', en: 'Provides the current numeric value of a range widget.' },
    'aria-valuetext': { zh: '以用户可理解的文本说明范围控件当前数值，例如等级名称。', en: 'Expresses a range widget’s current value as meaningful text, such as a named level.' },
} satisfies Record<string, ApiSemantic>

const actionEventProps = {
    onCopy: { zh: '监听复制操作，可通过 ClipboardEvent 读取或设置剪贴板数据。', en: 'Handles copy operations with access to clipboard data through ClipboardEvent.' },
    onCut: { zh: '监听剪切操作，可通过 ClipboardEvent 定制写入剪贴板的内容。', en: 'Handles cut operations and can customize clipboard content through ClipboardEvent.' },
    onPaste: { zh: '监听粘贴操作，通过 ClipboardEvent 读取将要插入的剪贴板内容。', en: 'Handles paste operations and exposes incoming clipboard content through ClipboardEvent.' },
    onCompositionend: { zh: '监听输入法组合会话完成或取消，适用于可编辑根元素。', en: 'Handles the end or cancellation of an IME composition session on an editable root.' },
    onCompositionstart: { zh: '监听可编辑根元素开始输入法组合会话。', en: 'Handles the start of an IME composition session on an editable root.' },
    onCompositionupdate: { zh: '监听输入法组合文本变化，适用于可编辑根元素。', en: 'Handles changes to IME composition text on an editable root.' },
    onDrag: { zh: '监听拖动源在原生拖放过程中持续发出的 drag 事件。', en: 'Handles repeated drag events on the source during native drag and drop.' },
    onDragend: { zh: '监听原生拖放操作结束，包括成功放下和取消拖动。', en: 'Handles the end of native dragging, including successful drops and cancellation.' },
    onDragenter: { zh: '监听被拖动元素或文本进入当前投放目标。', en: 'Handles a dragged element or text entering the drop target.' },
    onDragexit: { zh: '监听旧式 dragexit 事件，表示元素不再是拖放操作的直接目标；是否触发取决于浏览器支持。', en: 'Handles the legacy dragexit event when an element ceases to be the immediate drag target; dispatch depends on browser support.' },
    onDragleave: { zh: '监听被拖动元素或文本离开当前投放目标。', en: 'Handles a dragged element or text leaving the drop target.' },
    onDragover: { zh: '监听拖动内容经过投放目标；接受投放时通常需调用 preventDefault()。', en: 'Handles dragging over a drop target; accepting a drop typically requires preventDefault().' },
    onDragstart: { zh: '监听原生拖放开始，可设置 DragEvent.dataTransfer 中的拖动数据。', en: 'Handles the start of native dragging and can populate DragEvent.dataTransfer.' },
    onDrop: { zh: '监听拖动内容在有效目标上被放下，通过 dataTransfer 读取数据。', en: 'Handles a drop on a valid target and exposes transferred data through dataTransfer.' },
    onFocus: { zh: '监听根元素获得焦点；原生 focus 事件不冒泡。', en: 'Handles the root gaining focus; native focus events do not bubble.' },
    onFocusin: { zh: '监听根元素或其后代获得焦点的冒泡事件。', en: 'Handles bubbling focus-in events from the root or its descendants.' },
    onFocusout: { zh: '监听根元素或其后代失去焦点的冒泡事件。', en: 'Handles bubbling focus-out events from the root or its descendants.' },
    onBlur: { zh: '监听根元素失去焦点；原生 blur 事件不冒泡。', en: 'Handles the root losing focus; native blur events do not bubble.' },
    onChange: { zh: '监听输入或选择控件提交值变化的 change 事件；普通按钮激活不会产生该事件。', en: 'Handles committed value changes from an input or selection control; activating a regular button does not produce this event.' },
    onBeforeinput: { zh: '监听可编辑内容即将因用户输入而改变的事件，适用于支持输入的根元素。', en: 'Handles impending user edits to editable content on a supporting root element.' },
    onFormdata: { zh: '监听表单完成构造表单数据的事件，适用于表单根元素。', en: 'Handles completion of form-data construction on a form root element.' },
    onInput: { zh: '监听可编辑根元素因用户操作产生的输入值变化。', en: 'Handles user-driven value changes on an editable root element.' },
    onReset: { zh: '监听表单重置事件，适用于表单根元素；事件发生在 form 上。', en: 'Handles a form reset on a form root; the event is dispatched on the form.' },
    onSubmit: { zh: '监听表单提交事件，适用于表单根元素；普通提交按钮通过所属 form 发出该事件。', en: 'Handles submission on a form root; a regular submit button causes its owning form to dispatch this event.' },
    onInvalid: { zh: '监听支持约束校验的根控件校验失败；原生 invalid 事件不冒泡。', en: 'Handles failed constraint validation on a supporting root control; native invalid events do not bubble.' },
    onFullscreenchange: { zh: '监听根元素或其后代进入、退出全屏后产生的状态变化事件。', en: 'Handles fullscreen-state changes when the root or a descendant enters or leaves fullscreen.' },
    onFullscreenerror: { zh: '监听根元素或其后代的全屏请求失败。', en: 'Handles a failed fullscreen request from the root or a descendant.' },
    onLoad: { zh: '监听资源根元素完成加载，例如使用支持 load 的元素作为根时。', en: 'Handles completed resource loading when the root is an element that supports load events.' },
    onError: { zh: '监听根元素资源加载或使用失败，例如图片或媒体错误；不处理任意 Vue 组件异常。', en: 'Handles root resource failures, such as image or media errors; it is not a handler for arbitrary Vue component exceptions.' },
    onKeydown: { zh: '监听按键按下，包含按住按键时浏览器发出的重复事件。', en: 'Handles key presses, including browser-generated repeats while a key remains held.' },
    onKeypress: { zh: '监听已弃用的 keypress 字符按键事件；新的键盘交互使用 keydown 或 beforeinput。', en: 'Handles the deprecated keypress character-key event; use keydown or beforeinput for new keyboard interactions.' },
    onKeyup: { zh: '监听用户松开按键。', en: 'Handles the release of a keyboard key.' },
    onDblclick: { zh: '监听鼠标主按键完成双击。', en: 'Handles a completed double-click with the primary mouse button.' },
    onMousedown: { zh: '监听鼠标按键在元素上按下。', en: 'Handles a mouse button being pressed over the element.' },
    onMouseenter: { zh: '监听鼠标进入元素边界；与 mouseover 不同，此事件不冒泡。', en: 'Handles the mouse entering the element’s boundary; unlike mouseover, it does not bubble.' },
    onMouseleave: { zh: '监听鼠标离开元素及其后代边界；此事件不冒泡。', en: 'Handles the mouse leaving the element and its descendants; this event does not bubble.' },
    onMousemove: { zh: '监听鼠标在元素上移动。', en: 'Handles mouse movement over the element.' },
    onMouseout: { zh: '监听鼠标离开当前命中元素，包括移入其子元素时的冒泡事件。', en: 'Handles bubbling mouse-out events when leaving the current hit target, including movement into a child.' },
    onMouseover: { zh: '监听鼠标进入当前命中元素的冒泡事件。', en: 'Handles bubbling mouse-over events when entering the current hit target.' },
    onMouseup: { zh: '监听鼠标按键在元素上松开。', en: 'Handles a mouse button being released over the element.' },
    onAbort: { zh: '监听媒体根元素的加载被中止，且中止并非由加载错误导致。', en: 'Handles aborted loading on a media root when the interruption is not caused by a loading error.' },
    onCanplay: { zh: '监听媒体根元素已有足够数据开始播放，但尚不保证可连续播放至结束。', en: 'Handles a media root becoming able to start playback without assurance of uninterrupted playback to the end.' },
    onCanplaythrough: { zh: '监听浏览器估计媒体根元素可在无需停顿缓冲的情况下播放至结束。', en: 'Handles the browser estimating that a media root can play through without pausing to buffer.' },
    onDurationchange: { zh: '监听媒体根元素的时长信息发生变化。', en: 'Handles a change to the media root’s duration information.' },
    onEmptied: { zh: '监听媒体根元素从已加载状态恢复为空状态，例如重新加载媒体。', en: 'Handles a media root returning from a loaded state to an empty state, such as when reloading.' },
    onEncrypted: { zh: '监听媒体根元素遇到加密初始化数据，通过 MediaEncryptedEvent 获取该数据。', en: 'Handles encrypted initialization data encountered by a media root through MediaEncryptedEvent.' },
    onEnded: { zh: '监听媒体根元素播放到终点并停止。', en: 'Handles a media root reaching the end of playback and stopping.' },
    onLoadeddata: { zh: '监听媒体根元素当前播放位置的数据首次加载完成，通常为第一帧。', en: 'Handles the first loading of data at the media root’s current playback position, usually the first frame.' },
    onLoadedmetadata: { zh: '监听媒体根元素的元数据加载完成，例如时长或视频尺寸。', en: 'Handles a media root’s metadata becoming available, such as duration or video dimensions.' },
    onLoadstart: { zh: '监听媒体根元素开始加载资源。', en: 'Handles a media root beginning to load its resource.' },
    onPause: { zh: '监听媒体根元素进入暂停状态。', en: 'Handles a media root entering the paused state.' },
    onPlay: { zh: '监听媒体根元素的 paused 状态变为 false，表示播放已被请求。', en: 'Handles a media root’s paused state becoming false when playback is requested.' },
    onPlaying: { zh: '监听媒体根元素实际开始或恢复播放。', en: 'Handles a media root actually starting or resuming playback.' },
    onProgress: { zh: '监听媒体等支持资源进度事件的根元素加载数据时的进度通知。', en: 'Handles data-loading progress on a root that emits resource progress events, such as a media element.' },
    onRatechange: { zh: '监听媒体根元素的播放速率变化。', en: 'Handles a change to the media root’s playback rate.' },
    onSeeked: { zh: '监听媒体根元素完成播放位置跳转。', en: 'Handles a media root completing a seek to a playback position.' },
    onSeeking: { zh: '监听媒体根元素开始跳转到新的播放位置。', en: 'Handles a media root beginning to seek to a new playback position.' },
    onStalled: { zh: '监听媒体根元素仍在尝试获取数据但数据意外停止到达。', en: 'Handles a media root still attempting to fetch data when delivery unexpectedly stops.' },
    onSuspend: { zh: '监听浏览器主动暂停媒体根元素的数据获取。', en: 'Handles the browser intentionally suspending data fetching for a media root.' },
    onTimeupdate: { zh: '监听媒体根元素的 currentTime 更新。', en: 'Handles updates to a media root’s currentTime.' },
    onVolumechange: { zh: '监听媒体根元素的音量或静音状态变化。', en: 'Handles changes to a media root’s volume or muted state.' },
    onWaiting: { zh: '监听媒体根元素因暂时缺少数据而暂停继续播放。', en: 'Handles a media root waiting to continue playback because data is temporarily unavailable.' },
    onSelect: { zh: '监听支持文本选择的输入根元素中发生的文本选取。', en: 'Handles text selection in an input root that supports text selection.' },
    onScroll: { zh: '监听可滚动根元素的滚动位置变化。', en: 'Handles changes to the scroll position of a scrollable root.' },
    onScrollend: { zh: '监听可滚动根元素完成滚动，且相关滚动手势已结束。', en: 'Handles scrolling finishing on a scrollable root once the associated scrolling gesture has ended.' },
    onTouchcancel: { zh: '监听浏览器或设备中断触摸接触序列。', en: 'Handles the browser or device interrupting a sequence of touch contacts.' },
    onTouchend: { zh: '监听一个或多个触点离开触摸表面。', en: 'Handles one or more touch contacts leaving the touch surface.' },
    onTouchmove: { zh: '监听触点在触摸表面移动。', en: 'Handles touch contacts moving across the touch surface.' },
    onTouchstart: { zh: '监听一个或多个触点开始接触触摸表面。', en: 'Handles one or more touch contacts beginning on the touch surface.' },
    onAuxclick: { zh: '监听主按键之外的指针按键完成点击，例如鼠标中键。', en: 'Handles a completed click with a non-primary pointing-device button, such as the middle mouse button.' },
    onClick: {
        zh: '监听确认按钮的原生激活点击，通常由鼠标、触摸或键盘触发；Reka 的点击处理器同时请求关闭对话框。',
        en: 'Handles native activation clicks, typically from a mouse, touch, or keyboard; Reka’s click handler also requests dialog closure.',
        notes: {
            'zh-CN': ['异步回调不会使 AlertDialogAction 等待操作完成；需要业务控制关闭时，通过 AlertDialogRoot 的受控 open 状态管理。'],
            en: ['An asynchronous callback does not make AlertDialogAction wait for completion; use controlled open state on AlertDialogRoot when application logic must manage closure.'],
        },
    },
    onContextmenu: { zh: '监听用户请求打开上下文菜单，例如右键点击或上下文菜单键。', en: 'Handles a request to open a context menu, such as a right-click or the context-menu key.' },
    onGotpointercapture: { zh: '监听元素开始捕获指定指针，后续指针事件将定向到该元素。', en: 'Handles the element gaining capture of a pointer so subsequent pointer events target it.' },
    onLostpointercapture: { zh: '监听元素失去指定指针的捕获状态。', en: 'Handles the element losing capture of a pointer.' },
    onPointerdown: { zh: '监听指针进入活动按下状态，例如触摸接触或鼠标首次按键。', en: 'Handles a pointer becoming active, such as touch contact or the first mouse-button press.' },
    onPointermove: { zh: '监听指针位置或压力等指针属性发生变化。', en: 'Handles changes to pointer position or properties such as pressure.' },
    onPointerup: { zh: '监听指针结束活动按下状态。', en: 'Handles a pointer leaving its active pressed state.' },
    onPointercancel: { zh: '监听浏览器取消指针交互，例如接管触摸滚动手势。', en: 'Handles the browser cancelling pointer interaction, such as when taking over a touch-scrolling gesture.' },
    onPointerenter: { zh: '监听指针进入元素或其后代的命中边界；此事件不冒泡。', en: 'Handles a pointer entering the hit boundaries of the element or its descendants; it does not bubble.' },
    onPointerleave: { zh: '监听指针离开元素及其后代的命中边界；此事件不冒泡。', en: 'Handles a pointer leaving the hit boundaries of the element and its descendants; it does not bubble.' },
    onPointerover: { zh: '监听指针进入当前命中元素的冒泡事件。', en: 'Handles bubbling pointer-over events when a pointer enters the current hit target.' },
    onPointerout: { zh: '监听指针离开当前命中元素的冒泡事件，包括移入子元素的情况。', en: 'Handles bubbling pointer-out events when leaving the current hit target, including movement into a child.' },
    onBeforetoggle: { zh: '监听支持切换事件的根元素在打开或关闭前的状态变化，例如原生 popover 或 dialog。', en: 'Handles an impending open or close on a root supporting toggle events, such as a native popover or dialog.' },
    onToggle: { zh: '监听支持切换事件的根元素完成打开或关闭，例如 details、popover 或原生 dialog。', en: 'Handles a completed open or close on a supporting root, such as details, a popover, or a native dialog.' },
    onWheel: { zh: '监听滚轮或类似设备的滚动、缩放输入；该事件不等同于实际滚动位置变化。', en: 'Handles wheel-device scrolling or zooming input; it does not necessarily mean the scroll position changed.' },
    onAnimationcancel: { zh: '监听 CSS 动画在正常结束前被取消。', en: 'Handles a CSS animation being cancelled before normal completion.' },
    onAnimationstart: { zh: '监听 CSS 动画在延迟结束后开始播放。', en: 'Handles a CSS animation starting after its delay.' },
    onAnimationend: { zh: '监听 CSS 动画正常完成全部播放。', en: 'Handles a CSS animation completing normally.' },
    onAnimationiteration: { zh: '监听 CSS 动画的一次迭代结束并开始下一次迭代。', en: 'Handles a CSS animation finishing an iteration and beginning another.' },
    onSecuritypolicyviolation: { zh: '监听到达根元素的内容安全策略违规事件；浏览器通常将该事件派发到 document，按钮监听器不会接收所有文档级违规。', en: 'Handles content-security-policy violation events reaching the root; browsers normally dispatch these on document, so a button listener does not receive every document-level violation.' },
    onTransitioncancel: { zh: '监听 CSS 过渡在完成前被取消。', en: 'Handles a CSS transition being cancelled before completion.' },
    onTransitionend: { zh: '监听 CSS 过渡正常完成。', en: 'Handles a CSS transition completing normally.' },
    onTransitionrun: { zh: '监听 CSS 过渡创建，发生在可能的过渡延迟之前。', en: 'Handles a CSS transition being created, before any transition delay.' },
    onTransitionstart: { zh: '监听 CSS 过渡在延迟结束后开始变化。', en: 'Handles a CSS transition starting after its delay.' },
} satisfies Record<string, ApiSemantic>

const content = {
    complete: true,
    members: {
        AlertDialogContent: {
            props: {
                class: { zh: '合并到对话框内容面板的补充 CSS 类名。', en: 'Additional CSS classes merged into the dialog content panel.' },
                overlayClass: { zh: '合并到遮罩层的补充 CSS 类名，用于定制遮罩样式。', en: 'Additional CSS classes merged into the overlay for styling its backdrop.' },
            },
            slots: { default: { zh: '对话框面板内容，通常组合标题、描述和操作按钮；内容通过内置 Portal 渲染。', en: 'The dialog panel content, usually composing a title, description, and action buttons; it is rendered through the built-in Portal.' } },
        },
        AlertDialogAction: {
            props: {
                variant: { zh: '确认按钮的颜色、边框和交互状态样式变体。', en: 'The action button’s color, border, and interaction-state style variant.' },
                class: { zh: '合并到确认按钮根元素的补充 CSS 类名。', en: 'Additional CSS classes merged into the action button root.' },
                as: {
                    zh: '选择根元素的标签或组件；asChild 为真时使用默认插槽中的子元素。',
                    en: 'Selects the root tag or component; asChild uses the child from the default slot instead.',
                    fallback: {
                        'zh-CN': '未提供时由 Reka AlertDialogAction 使用 button。',
                        en: 'When omitted, Reka AlertDialogAction renders a button.',
                    },
                },
                asChild: {
                    zh: '将根属性、样式和关闭交互合并到默认插槽中的单个子元素，子元素需保留可访问的按钮交互。',
                    en: 'Merges root props, styles, and closure behavior into the single default-slot child, which must retain accessible button interaction.',
                    fallback: {
                        'zh-CN': '未提供时，底层 Primitive 使用 false。',
                        en: 'When omitted, the underlying Primitive uses false.',
                    },
                },
                ...actionHtmlProps,
                ...actionAriaProps,
                ...actionEventProps,
            },
            slots: { default: { zh: '确认按钮的文字或图标；asChild 为真时提供承接属性和交互的单个子元素。', en: 'The action button’s text or icon; with asChild, provide a single child that receives the props and interaction behavior.' } },
        },
        AlertDialogCancel: {
            props: { class: { zh: '合并到取消按钮根元素的补充 CSS 类名；按钮使用 outline 变体。', en: 'Additional CSS classes merged into the cancel button root, which uses the outline variant.' } },
            slots: { default: { zh: '取消按钮内容；激活按钮会请求关闭对话框，打开对话框时 Reka 默认尝试聚焦该按钮。', en: 'The cancel button content; activation requests closure, and Reka attempts to focus this button when the dialog opens.' } },
        },
        AlertDialogDescription: {
            props: { class: { zh: '合并到对话框描述元素的补充 CSS 类名。', en: 'Additional CSS classes merged into the dialog description element.' } },
            slots: { default: { zh: '解释待确认操作及其后果的描述内容，由 Reka 关联为对话框的无障碍描述。', en: 'Content explaining the operation and its consequences, associated by Reka with the dialog’s accessible description.' } },
        },
        AlertDialogFooter: {
            props: { class: { zh: '合并到操作按钮底部容器的补充 CSS 类名。', en: 'Additional CSS classes merged into the footer container for action buttons.' } },
            slots: { default: { zh: '底部操作内容，通常放置取消和确认按钮；未提供此插槽时不渲染底部容器。', en: 'Footer actions, usually cancel and confirmation buttons; the footer container is omitted when this slot is not provided.' } },
        },
        AlertDialogHeader: {
            props: { class: { zh: '合并到标题和描述头部容器的补充 CSS 类名。', en: 'Additional CSS classes merged into the header container for the title and description.' } },
            slots: { default: { zh: '头部内容，通常组合 AlertDialogTitle 和 AlertDialogDescription。', en: 'Header content, usually combining AlertDialogTitle and AlertDialogDescription.' } },
        },
        AlertDialogTitle: {
            props: { class: { zh: '合并到对话框标题元素的补充 CSS 类名。', en: 'Additional CSS classes merged into the dialog title element.' } },
            slots: {
                default: {
                    zh: '对话框标题，由 Reka 关联为无障碍名称；应提供说明待确认操作的标题。',
                    en: 'The dialog title, associated by Reka with its accessible name; supply a title describing the operation to confirm.',
                    fallback: {
                        'zh-CN': '未提供可渲染的插槽内容时显示英文占位文本 Alert；该占位文本不随语言切换。',
                        en: 'Without renderable slot content, the fallback is the English text Alert; this fallback is not localized.',
                    },
                },
            },
        },
    },
} satisfies ApiContent

export default content
