import type { ApiContent } from '../api-types'

const content = {
    complete: true,
    members: {
        DataTable: {
            props: {
                class: { zh: '追加到表格根容器的自定义 CSS 类。', en: 'Custom CSS classes added to the table root container.' },
                data: { zh: '要显示的行数据；泛型 T 会传递到列定义、行事件及编程接口。', en: 'The rows to display. Generic type T is carried through column definitions, row events, and the programmatic API.' },
                columns: { zh: '表格列定义，控制列头、取值、排序、筛选、渲染及列布局。', en: 'The column definitions that control headers, value access, sorting, filtering, rendering, and column layout.' },
                sortable: { zh: '启用可排序列的表头交互和排序数据处理；列可通过 sortable: false 单独关闭。', en: 'Enables sortable-column header interaction and sorted data; an individual column can opt out with sortable: false.' },
                filterable: { zh: '显示全局搜索输入框，并为声明 filterType 的列显示列筛选器。', en: 'Shows the global search input and column filters for columns that declare filterType.' },
                filterPlaceholder: { zh: '全局搜索输入框的占位文字及无障碍名称；未提供时使用当前语言的 dataTable.filterPlaceholder。', en: 'The global search input placeholder and accessible name; when omitted, the localized dataTable.filterPlaceholder message is used.' },
                selectable: { zh: '显示行选择框及表头全选框，并允许读取和导出选中行。', en: 'Shows row checkboxes and a select-all checkbox, and enables reading and exporting selected rows.' },
                paginated: { zh: '启用分页切片和分页控件。', en: 'Enables page slicing and the pagination controls.' },
                pageSize: { zh: '分页启用时每页显示的行数；未启用分页时数据不会按页切片。', en: 'The number of rows per page when pagination is enabled; data is not sliced into pages when pagination is disabled.' },
                pageSizeOptions: { zh: '分页控件中可选的每页行数。', en: 'The page sizes offered by the pagination control.' },
                loading: { zh: '显示加载遮罩和 loading 插槽内容。', en: 'Displays the loading overlay and the loading slot content.' },
                emptyMessage: { zh: '无数据状态的提示文本；未提供或为空字符串时使用当前语言的 dataTable.noData。', en: 'The empty-state message; when omitted or empty, the localized dataTable.noData message is used.' },
                rowKey: { zh: '提供行的唯一标识字段或取值函数；选中和展开行状态依赖解析后的字符串或数字键。', en: 'Provides a unique row-key field or accessor; row selection and expansion rely on the resolved string or number key.' },
                rowClickable: { zh: '使行可通过鼠标点击或 Enter 键触发 row-click 事件。', en: 'Makes a row activate the row-click event through pointer click or the Enter key.' },
                title: { zh: '未提供 header 插槽时显示在表格头部的标题。', en: 'The heading shown above the table when the header slot is not supplied.' },
                description: { zh: '未提供 header 插槽时显示在标题下方的说明文本。', en: 'The supporting text shown below the heading when the header slot is not supplied.' },
                section: { zh: '为表格根容器启用受限宽度并居中布局。', en: 'Applies a constrained width and centered layout to the table root container.' },
                framed: { zh: '控制根容器边框、阴影和圆角；设为 false 时移除这些外框样式。', en: 'Controls the root border, shadow, and rounded corners; false removes those frame styles.' },
                virtualScroll: { zh: '配置行虚拟滚动；enabled 为真时启用，rowHeight 可为固定行高或 auto 动态测量。', en: 'Configures row virtualization. It is enabled when enabled is true; rowHeight can be fixed or measured dynamically with auto.' },
                size: { zh: '设置表格尺寸变体。', en: 'Sets the table size variant.' },
                dense: { zh: '启用更紧凑的行和单元格间距。', en: 'Uses more compact row and cell spacing.' },
                striped: { zh: '控制相邻数据行的条纹背景。', en: 'Controls alternating background stripes on data rows.' },
                stickyHeader: { zh: '将表头设为滚动容器顶部的粘性区域。', en: 'Makes the header sticky at the top of its scrolling container.' },
                expandable: { zh: '显示行展开控制并允许呈现 expanded-row 插槽。', en: 'Shows row expansion controls and allows the expanded-row slot to render.' },
                expandRowKeys: { zh: '受控展开行键集合；键须与 rowKey 的解析结果一致，变更会同步内部展开状态。', en: 'The controlled set of expanded row keys. Keys must match rowKey resolution, and changes synchronize the internal expansion state.' },
                spanMethod: { zh: '对当前显示行和可见列的每个单元格计算合并范围；返回 rowspan、colspan，或不返回以使用默认跨度。', en: 'Calculates a merge span for each displayed row and visible column. Return rowspan and colspan, or nothing to use the default span.' },
            },
            events: {
                sort: { zh: '用户通过可排序表头交互后发出列 ID 和方向；方向为 asc、desc 或 null。', en: 'Emits the column ID and direction after the user interacts with a sortable header; direction is asc, desc, or null.' },
                filter: { zh: '筛选状态变化时发出当前全局及列筛选状态。', en: 'Emits the current global and column filter state when filtering changes.' },
                select: { zh: '用户切换行选择或当前页全选状态后发出所选行数据数组。', en: 'Emits the selected row data array after the user toggles a row or the current-page select-all control.' },
                'page-change': { zh: '用户导航到不同页码后发出实际生效的页码；页码未变化时不发出。', en: 'Emits the page number after user navigation changes the current page; no event is emitted when the page stays the same.' },
                'page-size-change': { zh: '用户在分页控件中选择新的每页行数后发出该行数。', en: 'Emits the new page size after the user selects it in the pagination control.' },
                'expand-change': { zh: '行展开状态切换时发出对应行数据和新的展开布尔值。', en: 'Emits the row data and its new expanded boolean when the row expansion state toggles.' },
                'row-click': { zh: 'rowClickable 启用时，行被鼠标点击或按 Enter 激活后发出行数据；事件来自按钮、输入框、链接等交互元素时跳过。', en: 'When rowClickable is enabled, emits row data after a pointer click or Enter activation; events originating inside buttons, inputs, links, or other interactive elements are ignored.' },
                export: { zh: '表格导出控件操作时发出所选格式和当前选中行数组。', en: 'Emits the selected format and current selected-row array when a table export control is activated.' },
            },
            slots: {
                header: { zh: '替换表格默认头部；未提供时根据 title 和 description 渲染标题区。', en: 'Replaces the default table header; when omitted, the heading area is rendered from title and description.' },
                toolbar: { zh: '全局筛选工具栏的扩展内容；启用 filterable 时显示在搜索输入框旁。', en: 'Additional content for the global filtering toolbar; when filterable is enabled, it appears beside the search input.' },
                'expanded-row': { zh: '展开行的附加内容，作用域提供 row 和当前展示列表中的 index；仅在该行展开且 expandable 启用时渲染。', en: 'Additional expanded-row content with row and its index in the displayed list; rendered only for an expanded row when expandable is enabled.' },
                empty: { zh: '替换无数据状态内容；仅当没有可显示数据且未处于 loading 状态时渲染。', en: 'Replaces the empty-state content; rendered only when there is no display data and loading is false.' },
                loading: { zh: '替换加载遮罩内容；仅在 loading 为真时渲染。', en: 'Replaces the loading overlay content; rendered only when loading is true.' },
                footer: { zh: '在表格及加载区域之后渲染的页脚扩展内容。', en: 'Additional footer content rendered after the table and loading area.' },
            },
            exposes: {
                sort: { zh: '表格排序命名空间，包含 toggleSort 方法和只读 sortState。', en: 'The table sorting namespace, containing toggleSort and the read-only sortState.' },
                'sort.toggleSort': { zh: '为给定列 ID 切换排序方向；需要 sortable 开启且列未禁用排序，顺序为升序、降序、取消。', en: 'Toggles sorting for a column ID. Sorting must be enabled and the column must not opt out; the cycle is ascending, descending, then cleared.' },
                'sort.sortState': { zh: '只读响应式排序状态，包含当前列 ID 和 asc、desc 或 null 方向。', en: 'The read-only reactive sort state containing the current column ID and asc, desc, or null direction.' },
                filter: { zh: '表格筛选命名空间，提供状态读取及设置全局或完整筛选条件的方法。', en: 'The table filtering namespace, providing state access and methods to set global or complete filter criteria.' },
                'filter.filterState': { zh: '只读响应式筛选状态，包含可选的 global 值和按列 ID 索引的 columns。', en: 'The read-only reactive filter state, with an optional global value and columns indexed by column ID.' },
                'filter.setGlobalFilter': { zh: '设置全局搜索关键字。', en: 'Sets the global search keyword.' },
                'filter.setFilterState': { zh: '用给定的 DataTableFilterState 更新完整筛选状态。', en: 'Replaces the complete filtering state with the supplied DataTableFilterState.' },
                selection: { zh: '表格选择命名空间，提供行选择操作、选中行键状态及读取选中行数据的方法。', en: 'The table selection namespace, providing row-selection actions, selected-key state, and a method to read selected row data.' },
                'selection.toggleRow': { zh: '切换指定行的选择状态；需要 selectable 开启。', en: 'Toggles selection for the specified row; selectable must be enabled.' },
                'selection.toggleAllRows': { zh: '切换当前显示页所有行的选择状态；取消时保留其他页或筛选隐藏行的选择。', en: 'Toggles selection for all rows on the current display page; clearing preserves selections from other pages or filtered-out rows.' },
                'selection.clearSelection': { zh: '清空全部已选行键。', en: 'Clears all selected row keys.' },
                'selection.getSelectedRows': { zh: '返回当前所选行对应的完整行数据数组。', en: 'Returns the full row data array for the current selection.' },
                'selection.selectedRows': { zh: '只读浅响应式集合，保存已选行键。', en: 'The read-only shallow-reactive set of selected row keys.' },
                'selection.isAllSelected': { zh: '只读计算状态，表示当前显示页的全部行是否已选中。', en: 'A read-only computed state indicating whether all rows on the current display page are selected.' },
                pagination: { zh: '表格分页命名空间，包含页码和页数状态以及分页控制方法。', en: 'The table pagination namespace, containing page state and pagination control methods.' },
                'pagination.goToPage': { zh: '跳转到指定页；页码会限制在有效范围，并返回页码是否实际改变。', en: 'Navigates to the requested page, clamps it to the valid range, and returns whether the page changed.' },
                'pagination.nextPage': { zh: '尝试前往下一页，并返回页码是否实际改变。', en: 'Attempts to move to the next page and returns whether the page changed.' },
                'pagination.previousPage': { zh: '尝试前往上一页，并返回页码是否实际改变。', en: 'Attempts to move to the previous page and returns whether the page changed.' },
                'pagination.setPageSize': { zh: '设置每页行数并将当前页重置为第一页；非法尺寸会被忽略。', en: 'Sets the page size and resets the current page to the first page; invalid sizes are ignored.' },
                'pagination.pageIndex': { zh: '只读响应式当前页码，从 1 开始。', en: 'The read-only reactive current page number, starting at 1.' },
                'pagination.pageCount': { zh: '只读计算的总页数；没有行数据时至少为 1。', en: 'The read-only computed page count; it is at least 1 when there are no rows.' },
                expand: { zh: '表格行展开命名空间，提供切换、查询及读取已展开行键的方法和状态。', en: 'The table row-expansion namespace, providing toggle and query methods plus the expanded-key state.' },
                'expand.toggleRow': { zh: '切换指定行的展开状态并发出 expand-change 事件。', en: 'Toggles expansion for the specified row and emits expand-change.' },
                'expand.isRowExpanded': { zh: '查询指定行当前是否展开。', en: 'Checks whether the specified row is currently expanded.' },
                'expand.expandedRowKeys': { zh: '保存当前已展开行键的浅响应式集合。', en: 'The shallow-reactive set containing the currently expanded row keys.' },
            },
        },
        DataTableColumnFilter: {
            props: {
                column: { zh: '此筛选控件对应的列定义；其 filterType 和 filterOptions 决定筛选器控件。', en: 'The column definition for this filter control; its filterType and filterOptions determine the filter UI.' },
                filterState: { zh: '当前只读筛选状态；控件据此显示对应列的文本、选项或日期范围值。', en: 'The current read-only filter state, used to display this column’s text, option, or date-range value.' },
                headerLabel: { zh: '用于构造筛选控件标题的列头显示文本。', en: 'The displayed column-header text used to label the filter control.' },
            },
            events: {
                'update:filterState': { zh: '筛选值变化时发出只包含当前列增量的状态对象；列值为 null 表示清除该列筛选。', en: 'Emits a state object containing only the current column change when its filter value changes; a null column value clears that column filter.' },
            },
        },
    },
    supplements: {
        DataTable: [
            {
                name: 'cell-{columnId}',
                kind: 'slots',
                type: '{ row: T; value: unknown }',
                origin: 'supplement',
                source: { file: 'packages/ui/src/components/data-table/DataTable.vue' },
                description: {
                    'zh-CN': '为指定列提供自定义单元格内容；插槽名为 cell-{columnId}，作用域提供当前行 row 和单元格值 value。',
                    en: 'Provides custom content for a column cell. Use the cell-{columnId} slot name; its scope exposes the current row and cell value.',
                },
                notes: {
                    'zh-CN': ['仅用于普通数据列；未提供时回退到列的 cell 渲染函数或默认单元格值。'],
                    en: ['Used only for regular data columns. If absent, the table falls back to the column cell renderer or the default cell value.'],
                },
            },
        ],
    },
} satisfies ApiContent

export default content
