export const componentDependencies: Record<string, string[]> = {
    button: ['@radix-ui/react-slot', 'class-variance-authority'],
    card: ['class-variance-authority'],
    input: ['class-variance-authority'],
    textarea: [],
    label: ['class-variance-authority'],
    badge: ['class-variance-authority'],
    dialog: ['@radix-ui/react-dialog'],
    popover: ['@radix-ui/react-popover'],
    tooltip: ['@radix-ui/react-tooltip'],
    'dropdown-menu': ['@radix-ui/react-dropdown-menu'],
    select: ['@radix-ui/react-select'],
    tabs: ['@radix-ui/react-tabs'],
    table: [],
    alert: ['class-variance-authority'],
    avatar: ['class-variance-authority'],
    separator: ['@radix-ui/react-separator'],
    switch: ['@radix-ui/react-switch'],
    checkbox: ['@radix-ui/react-checkbox'],
    pagination: [],
    spinner: [],
    toast: [],
    skeleton: [],
    calendar: ['react-day-picker'],
    'context-menu': ['@radix-ui/react-context-menu'],
    command: ['cmdk'],
    combobox: ['cmdk', '@radix-ui/react-popover'],
    'scroll-area': ['@radix-ui/react-scroll-area'],
};

export const componentImports: Record<string, string[]> = {
    button: ['Button', 'buttonVariants'],
    card: ['Card', 'CardHeader', 'CardTitle', 'CardDescription', 'CardContent', 'CardFooter'],
    input: ['Input'],
    textarea: ['Textarea'],
    label: ['Label'],
    badge: ['Badge', 'badgeVariants'],
    dialog: [
        'Dialog',
        'DialogTrigger',
        'DialogContent',
        'DialogHeader',
        'DialogFooter',
        'DialogTitle',
        'DialogDescription',
        'DialogClose',
    ],
    popover: ['Popover', 'PopoverTrigger', 'PopoverContent'],
    tooltip: ['Tooltip', 'TooltipTrigger', 'TooltipContent', 'TooltipProvider'],
    'dropdown-menu': [
        'DropdownMenu',
        'DropdownMenuTrigger',
        'DropdownMenuContent',
        'DropdownMenuItem',
        'DropdownMenuCheckboxItem',
        'DropdownMenuRadioItem',
        'DropdownMenuLabel',
        'DropdownMenuSeparator',
        'DropdownMenuShortcut',
        'DropdownMenuGroup',
        'DropdownMenuSub',
        'DropdownMenuSubContent',
        'DropdownMenuSubTrigger',
        'DropdownMenuRadioGroup',
    ],
    select: [
        'Select',
        'SelectGroup',
        'SelectValue',
        'SelectTrigger',
        'SelectContent',
        'SelectLabel',
        'SelectItem',
        'SelectSeparator',
    ],
    tabs: ['Tabs', 'TabsList', 'TabsTrigger', 'TabsContent'],
    table: [
        'Table',
        'TableHeader',
        'TableBody',
        'TableFooter',
        'TableHead',
        'TableRow',
        'TableCell',
        'TableCaption',
    ],
    alert: ['Alert', 'AlertTitle', 'AlertDescription'],
    avatar: ['Avatar', 'AvatarImage', 'AvatarFallback'],
    separator: ['Separator'],
    switch: ['Switch'],
    checkbox: ['Checkbox'],
    pagination: [
        'Pagination',
        'PaginationContent',
        'PaginationEllipsis',
        'PaginationItem',
        'PaginationLink',
        'PaginationNext',
        'PaginationPrevious',
    ],
    spinner: ['Spinner'],
    toast: [
        'Toast',
        'ToastAction',
        'ToastClose',
        'ToastDescription',
        'ToastTitle',
        'ToastProvider',
        'ToastViewport',
    ],
    skeleton: ['Skeleton'],
    calendar: ['Calendar'],
    'context-menu': [
        'ContextMenu',
        'ContextMenuTrigger',
        'ContextMenuContent',
        'ContextMenuItem',
        'ContextMenuCheckboxItem',
        'ContextMenuRadioItem',
        'ContextMenuLabel',
        'ContextMenuSeparator',
        'ContextMenuShortcut',
        'ContextMenuGroup',
        'ContextMenuSub',
        'ContextMenuSubContent',
        'ContextMenuSubTrigger',
        'ContextMenuRadioGroup',
    ],
    command: [
        'Command',
        'CommandDialog',
        'CommandInput',
        'CommandList',
        'CommandEmpty',
        'CommandGroup',
        'CommandItem',
        'CommandShortcut',
        'CommandSeparator',
    ],
    combobox: ['Combobox', 'ComboboxMulti'],
    'scroll-area': ['ScrollArea', 'ScrollBar'],
};
