export { DialogRoot as Dialog, DialogTrigger, DialogPortal, DialogClose } from 'reka-ui'
export { default as DialogOverlay } from './components/dialog/DialogOverlay.vue'
export { default as DialogContent } from './components/dialog/DialogContent.vue'
export { default as DialogEnhanced } from './components/dialog/DialogEnhanced.vue'
export { default as DialogHeader } from './components/dialog/DialogHeader.vue'
export { default as DialogFooter } from './components/dialog/DialogFooter.vue'
export { default as DialogTitle } from './components/dialog/DialogTitle.vue'
export { default as DialogDescription } from './components/dialog/DialogDescription.vue'
export { dialogContentVariants, dialogCloseVariants } from './components/dialog/dialog-variants'
