export { default as Table } from './components/table/Table.vue'
export { default as TableHeader } from './components/table/TableHeader.vue'
export { default as TableBody } from './components/table/TableBody.vue'
export { default as TableFooter } from './components/table/TableFooter.vue'
export { default as TableRow } from './components/table/TableRow.vue'
export { default as TableHead } from './components/table/TableHead.vue'
export { default as TableCell } from './components/table/TableCell.vue'
export { default as TableCaption } from './components/table/TableCaption.vue'
export { tableVariants, tableHeaderVariants, tableHeadVariants, tableFooterVariants, tableRowVariants, tableCellVariants } from './components/table/table-variants'
