export type {
    Size,
    CompactSize,
    Variant,
    Orientation,
    Alignment,
    IconComponent,
    ResizeCorner,
    MoveDirection,
    EventHandler,
    OptionalEventHandler,
    ComponentProps,
    ComponentEmits,
    ComponentSlots,
    Nullable,
    MaybeUndefined,
    DeepPartial,
    DeepReadonly,
    ArrayElement,
    RecordValue,
    PartialBy,
    RequiredBy,
} from './types/common'
