import type { ComponentMeta } from './types.js';

export const COMPONENTS: Record<string, ComponentMeta> = {
    alert: { name: 'alert', dependencies: ['lucide-vue-next'] },
    avatar: { name: 'avatar', dependencies: ['reka-ui'] },
    badge: { name: 'badge', dependencies: [] },
    button: { name: 'button', dependencies: ['reka-ui', 'lucide-vue-next'] },
    calendar: { name: 'calendar', dependencies: ['v-calendar', 'lucide-vue-next'] },
    card: { name: 'card', dependencies: [] },
    checkbox: { name: 'checkbox', dependencies: ['reka-ui', 'lucide-vue-next'] },
    combobox: {
        name: 'combobox',
        dependencies: ['reka-ui', 'lucide-vue-next'],
    },
    command: { name: 'command', dependencies: ['reka-ui'] },
    dialog: { name: 'dialog', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'dropdown-menu': {
        name: 'dropdown-menu',
        dependencies: ['reka-ui', 'lucide-vue-next'],
    },
    input: { name: 'input', dependencies: [] },
    label: { name: 'label', dependencies: ['reka-ui'] },
    pagination: { name: 'pagination', dependencies: ['lucide-vue-next'] },
    popover: { name: 'popover', dependencies: ['reka-ui'] },
    'scroll-area': { name: 'scroll-area', dependencies: ['reka-ui'] },
    select: { name: 'select', dependencies: ['reka-ui', 'lucide-vue-next'] },
    separator: { name: 'separator', dependencies: ['reka-ui'] },
    skeleton: { name: 'skeleton', dependencies: [] },
    spinner: { name: 'spinner', dependencies: [] },
    'submit-button': { name: 'submit-button', dependencies: ['lucide-vue-next'] },
    switch: { name: 'switch', dependencies: ['reka-ui'] },
    table: { name: 'table', dependencies: [] },
    tabs: { name: 'tabs', dependencies: ['reka-ui'] },
    textarea: { name: 'textarea', dependencies: [] },
    toast: { name: 'toast', dependencies: ['lucide-vue-next'] },
    tooltip: { name: 'tooltip', dependencies: ['reka-ui'] },
    'saas-pricing': { name: 'saas-pricing', dependencies: ['lucide-vue-next'] },
    'dashboard-stats': { name: 'dashboard-stats', dependencies: ['lucide-vue-next'] },
    form: { name: 'form', dependencies: ['vee-validate', '@vee-validate/zod', 'zod', 'reka-ui'] },
    'alert-dialog': { name: 'alert-dialog', dependencies: ['reka-ui'] },
    sheet: { name: 'sheet', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'radio-group': { name: 'radio-group', dependencies: ['reka-ui', 'lucide-vue-next'] },
    slider: { name: 'slider', dependencies: ['reka-ui'] },
    progress: { name: 'progress', dependencies: ['reka-ui'] },
    toggle: { name: 'toggle', dependencies: ['reka-ui'] },
    'toggle-group': { name: 'toggle-group', dependencies: ['reka-ui'] },
    'brutalist-hero': { name: 'brutalist-hero', dependencies: ['lucide-vue-next'] },
    'pricing-section': { name: 'pricing-section', dependencies: ['lucide-vue-next'] },
    'auth-card': { name: 'auth-card', dependencies: ['lucide-vue-next'] },
    'dashboard-shell': { name: 'dashboard-shell', dependencies: ['lucide-vue-next'] },
    'empty-state': { name: 'empty-state', dependencies: ['lucide-vue-next'] },
    'waitlist-page': { name: 'waitlist-page', dependencies: ['lucide-vue-next'] },
    accordion: { name: 'accordion', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'tags-input': { name: 'tags-input', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'number-input': { name: 'number-input', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'copy-to-clipboard': { name: 'copy-to-clipboard', dependencies: ['lucide-vue-next'] },
    breadcrumb: { name: 'breadcrumb', dependencies: ['reka-ui', 'lucide-vue-next'] },
    marquee: { name: 'marquee', dependencies: [] },
    'before-after': { name: 'before-after', dependencies: [] },
    'code-block': { name: 'code-block', dependencies: ['lucide-vue-next'] },
    timeline: { name: 'timeline', dependencies: ['reka-ui', 'lucide-vue-next'] },
};

export const AVAILABLE_COMPONENTS = Object.keys(COMPONENTS);
