import type { ComponentMeta } from './types.js';

export const COMPONENTS: Record<string, ComponentMeta> = {
    alert: { name: 'alert', dependencies: ['lucide-vue-next'] },
    avatar: { name: 'avatar', dependencies: ['reka-ui'] },
    badge: { name: 'badge', dependencies: [] },
    button: { name: 'button', dependencies: ['reka-ui', 'lucide-vue-next'] },
    calendar: { name: 'calendar', dependencies: ['v-calendar', 'lucide-vue-next'] },
    card: { name: 'card', dependencies: [] },
    checkbox: { name: 'checkbox', dependencies: ['reka-ui', 'lucide-vue-next'] },
    combobox: {
        name: 'combobox',
        dependencies: ['reka-ui', 'lucide-vue-next'],
    },
    command: { name: 'command', dependencies: ['reka-ui'] },
    dialog: { name: 'dialog', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'dropdown-menu': {
        name: 'dropdown-menu',
        dependencies: ['reka-ui', 'lucide-vue-next'],
    },
    input: { name: 'input', dependencies: [] },
    label: { name: 'label', dependencies: ['reka-ui'] },
    pagination: { name: 'pagination', dependencies: ['lucide-vue-next'] },
    popover: { name: 'popover', dependencies: ['reka-ui'] },
    'scroll-area': { name: 'scroll-area', dependencies: ['reka-ui'] },
    select: { name: 'select', dependencies: ['reka-ui', 'lucide-vue-next'] },
    separator: { name: 'separator', dependencies: ['reka-ui'] },
    skeleton: { name: 'skeleton', dependencies: [] },
    spinner: { name: 'spinner', dependencies: [] },
    'submit-button': { name: 'submit-button', dependencies: ['lucide-vue-next'] },
    switch: { name: 'switch', dependencies: ['reka-ui'] },
    table: { name: 'table', dependencies: [] },
    tabs: { name: 'tabs', dependencies: ['reka-ui'] },
    textarea: { name: 'textarea', dependencies: [] },
    toast: { name: 'toast', dependencies: ['lucide-vue-next'] },
    tooltip: { name: 'tooltip', dependencies: ['reka-ui'] },
    'saas-pricing': { name: 'saas-pricing', dependencies: ['lucide-vue-next'] },
    'dashboard-stats': { name: 'dashboard-stats', dependencies: ['lucide-vue-next'] },
    form: { name: 'form', dependencies: ['vee-validate', '@vee-validate/zod', 'zod', 'reka-ui'] },
    'alert-dialog': { name: 'alert-dialog', dependencies: ['reka-ui'] },
    sheet: { name: 'sheet', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'radio-group': { name: 'radio-group', dependencies: ['reka-ui', 'lucide-vue-next'] },
    slider: { name: 'slider', dependencies: ['reka-ui'] },
    progress: { name: 'progress', dependencies: ['reka-ui'] },
    toggle: { name: 'toggle', dependencies: ['reka-ui'] },
    'toggle-group': { name: 'toggle-group', dependencies: ['reka-ui'] },
    'brutalist-hero': { name: 'brutalist-hero', dependencies: ['lucide-vue-next'] },
    'pricing-section': { name: 'pricing-section', dependencies: ['lucide-vue-next'] },
    'auth-card': { name: 'auth-card', dependencies: ['lucide-vue-next'] },
    'dashboard-shell': { name: 'dashboard-shell', dependencies: ['lucide-vue-next'] },
    'empty-state': { name: 'empty-state', dependencies: ['lucide-vue-next'] },
    'waitlist-page': { name: 'waitlist-page', dependencies: ['lucide-vue-next'] },
    accordion: { name: 'accordion', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'tags-input': { name: 'tags-input', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'number-input': { name: 'number-input', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'copy-to-clipboard': { name: 'copy-to-clipboard', dependencies: ['lucide-vue-next'] },
    breadcrumb: { name: 'breadcrumb', dependencies: ['reka-ui', 'lucide-vue-next'] },
    marquee: { name: 'marquee', dependencies: [] },
    'before-after': { name: 'before-after', dependencies: [] },
    'code-block': { name: 'code-block', dependencies: ['lucide-vue-next'] },
    timeline: { name: 'timeline', dependencies: ['reka-ui', 'lucide-vue-next'] },
    carousel: { name: 'carousel', dependencies: ['embla-carousel-vue', 'lucide-vue-next'] },
    'tree-view': { name: 'tree-view', dependencies: ['reka-ui', 'lucide-vue-next'] },
    kanban: { name: 'kanban', dependencies: ['lucide-vue-next'] },
    'chat-bubble': { name: 'chat-bubble', dependencies: ['reka-ui', 'lucide-vue-next'] },
    kbd: { name: 'kbd', dependencies: [] },
    counter: { name: 'counter', dependencies: [] },
    stepper: { name: 'stepper', dependencies: ['lucide-vue-next'] },
    'card-3d': { name: 'card-3d', dependencies: [] },
    'glitch-text': { name: 'glitch-text', dependencies: [] },
    'scratch-card': { name: 'scratch-card', dependencies: [] },
    'sketchy-chart': { name: 'sketchy-chart', dependencies: [] },
    'hardcore-input': { name: 'hardcore-input', dependencies: [] },
    'testimonial-card': { name: 'testimonial-card', dependencies: ['lucide-vue-next'] },
    'blog-card': { name: 'blog-card', dependencies: ['lucide-vue-next'] },
    'file-card': { name: 'file-card', dependencies: ['lucide-vue-next'] },
    'quick-actions': { name: 'quick-actions', dependencies: ['lucide-vue-next'] },
    'faq-section': { name: 'faq-section', dependencies: ['lucide-vue-next'] },
    'tabs-nav': { name: 'tabs-nav', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'header-section': { name: 'header-section', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'footer-section': { name: 'footer-section', dependencies: ['lucide-vue-next'] },
    'not-found-page': { name: 'not-found-page', dependencies: ['lucide-vue-next'] },
    'loading-page': { name: 'loading-page', dependencies: ['lucide-vue-next'] },
    'error-card': { name: 'error-card', dependencies: ['lucide-vue-next'] },
    'success-card': { name: 'success-card', dependencies: ['lucide-vue-next'] },
    'search-widget': { name: 'search-widget', dependencies: ['lucide-vue-next'] },
    'feedback-form': { name: 'feedback-form', dependencies: ['lucide-vue-next'] },
    'stepper-section': { name: 'stepper-section', dependencies: ['lucide-vue-next'] },
    'cookie-consent': { name: 'cookie-consent', dependencies: ['lucide-vue-next'] },
    'data-table-section': { name: 'data-table-section', dependencies: ['lucide-vue-next'] },
    'settings-page': { name: 'settings-page', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'blog-list-page': { name: 'blog-list-page', dependencies: ['lucide-vue-next'] },
    'activity-log-page': { name: 'activity-log-page', dependencies: ['lucide-vue-next'] },
    'profile-page': { name: 'profile-page', dependencies: ['lucide-vue-next'] },
    'chart-section': { name: 'chart-section', dependencies: ['reka-ui', 'lucide-vue-next'] },
    'gallery-section': { name: 'gallery-section', dependencies: ['embla-carousel-vue', 'lucide-vue-next'] },
    'upload-card': { name: 'upload-card', dependencies: ['lucide-vue-next'] },
    'overview-page': { name: 'overview-page', dependencies: ['lucide-vue-next'] },
} as const;

export const AVAILABLE_COMPONENTS = Object.keys(COMPONENTS);
