/**
 * Shared logic for generating `index.ts` barrel file content.
 *
 * Used by:
 *   - packages/ui/scripts/generate-component-index.ts (writes to disk during prebuild)
 *   - packages/registry/scripts/build-registry.ts (generates content inline for registry JSON)
 *
 * The `index.ts` barrel is a derived artifact — its content is fully determined
 * by the list of source files in the component directory. It is gitignored and
 * must NOT be scanned by scan-component-files.ts (which would create a circular
 * dependency: scanner picks up index.ts → manifest includes it → registry build
 * tries to read it from disk → fails on clean checkout where it hasn't been
 * generated yet).
 */

const AUTO_GEN_HEADER = `/**
 * AUTO-GENERATED by prebuild — DO NOT EDIT.
 * To add public exports, edit the underlying .vue/.ts file (it will be
 * picked up automatically on the next prebuild).
 */
`;

const TEST_FILE_PATTERN = /\.(test|spec)\.(ts|js|tsx|jsx)$/;
const BROWSER_TEST_PATTERN = /\.browser\.test\.(ts|js)$/;
const SKIP_FILES = new Set(['index.ts']);

function vueFileNameToExportName(fileName: string): string {
    return fileName.replace(/\.vue$/, '');
}

function tsFileNameToModuleSpec(fileName: string): string {
    return `./${fileName.replace(/\.ts$/, '')}`;
}

/**
 * Generate the `index.ts` barrel file content from a list of component file names.
 *
 * Pattern:
 *   - `.vue` files → `export { default as PascalCase } from './File.vue'` + `export type *`
 *   - `.ts` files  → `export * from './file'`
 *   - `.css` files → skipped (side-effect imports handled by vite)
 *   - `index.ts`   → skipped (the file being generated)
 *   - test files   → skipped
 *
 * @param files - List of file names in the component directory (e.g. ['Accordion.vue', 'accordion-variants.ts'])
 * @returns The full `index.ts` file content as a string.
 */
export function buildComponentIndexContent(files: string[]): string {
    const lines: string[] = [AUTO_GEN_HEADER];

    const sortedFiles = [...files].sort();
    for (const file of sortedFiles) {
        if (SKIP_FILES.has(file)) continue;
        if (TEST_FILE_PATTERN.test(file)) continue;
        if (BROWSER_TEST_PATTERN.test(file)) continue;

        if (file.endsWith('.vue')) {
            const exportName = vueFileNameToExportName(file);
            lines.push(`export { default as ${exportName} } from './${file}'`);
            lines.push(`export type * from './${file}'`);
        } else if (file.endsWith('.ts')) {
            lines.push(`export * from '${tsFileNameToModuleSpec(file)}'`);
        }
    }

    return lines.join('\n') + '\n';
}
