import type { RegistryComponentMeta } from './types.js';

export const COMPONENTS: Record<string, RegistryComponentMeta> = {
    accordion: {
        titleZh: '折叠面板',
        category: 'navigation',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Collapsible content sections with keyboard navigation.',
    },
    alert: {
        titleZh: '提示',
        category: 'feedback',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Contextual alert banners with variants for info, success, warning, and error states.',
    },
    'alert-dialog': {
        titleZh: '提示对话框',
        category: 'overlay',
        dependencies: ['reka-ui'],
        description: 'Confirmation dialog requiring explicit user action before proceeding.',
    },
    'auth-card': {
        titleZh: '认证卡片',
        category: 'marketing',
        dependencies: ['@lucide/vue'],
        description: 'Authentication card with login, register, and password recovery forms.',
        kind: 'block',
        sidebarGroup: 'blocks-cards',
    },
    avatar: {
        titleZh: '头像',
        category: 'data-display',
        dependencies: ['reka-ui'],
        description: 'User avatar with image, fallback initials, and status indicator support.',
    },
    backtop: {
        titleZh: '回到顶部',
        category: 'navigation',
        dependencies: ['@lucide/vue'],
        description: 'Brutalist back-to-top button with scroll detection and click behavior.',
        sidebarGroup: 'utility',
    },
    badge: {
        titleZh: '徽标',
        category: 'feedback',
        dependencies: ['@lucide/vue'],
        description: 'Inline status badges and labels with color variants.',
    },
    'before-after': {
        titleZh: '对比滑块',
        category: 'visual-effect',
        dependencies: ['@lucide/vue'],
        description: 'Side-by-side image comparison with draggable slider.',
    },
    breadcrumb: {
        titleZh: '面包屑',
        category: 'navigation',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Hierarchical navigation breadcrumb with separator and ellipsis.',
    },
    'brutalist-hero': {
        titleZh: '英雄区',
        category: 'marketing',
        dependencies: ['@lucide/vue'],
        description: 'Full-width hero section with bold typography and call-to-action.',
        kind: 'block',
        sidebarGroup: 'blocks-sections',
    },
    button: {
        titleZh: '按钮',
        category: 'action',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Interactive button with loading state, icon support, and multiple style variants.',
    },
    calendar: {
        titleZh: '日历',
        category: 'data-display',
        dependencies: ['reka-ui', 'v-calendar', '@lucide/vue'],
        description: 'Date calendar with single and range selection powered by v-calendar.',
        sidebarGroup: 'date-time',
    },
    card: {
        titleZh: '卡片',
        category: 'layout',
        dependencies: [],
        description: 'Content card container with header, body, footer, and description sections.',
    },
    'card-3d': {
        titleZh: '3D 悬浮卡片',
        category: 'layout',
        dependencies: [],
        description: 'Interactive card with 3D tilt effect on mouse movement.',
    },
    carousel: {
        titleZh: '轮播图',
        category: 'data-display',
        dependencies: ['embla-carousel-vue', '@lucide/vue'],
        description: 'Image and content carousel with navigation and autoplay.',
    },
    cascader: {
        titleZh: '级联选择器',
        category: 'form',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Cascading selector with multi-level option navigation and search support.',
    },
    'chat-bubble': {
        titleZh: '聊天气泡',
        category: 'data-display',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Chat message bubbles with avatar and timestamp.',
    },
    checkbox: {
        titleZh: '复选框',
        category: 'form',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Accessible checkbox with label and indeterminate state support.',
    },
    'code-block': {
        titleZh: '代码块',
        category: 'data-display',
        dependencies: ['@lucide/vue', 'prismjs'],
        description: 'Syntax-highlighted code display with language selector and copy button.',
    },
    'color-mode-switcher': {
        titleZh: '颜色模式切换',
        category: 'utility',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Toggle between light, dark, and system color modes.',
    },
    'color-picker': {
        titleZh: '颜色选择器',
        category: 'form',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Color picker with palette, input, history, and swatches.',
    },
    combobox: {
        titleZh: '组合框',
        category: 'form',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Searchable dropdown with single and multi-select modes.',
    },
    command: {
        titleZh: '命令面板',
        category: 'overlay',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Command palette with keyboard navigation and fuzzy search.',
    },
    'cookie-consent': {
        titleZh: 'Cookie 同意',
        category: 'marketing',
        dependencies: ['@lucide/vue'],
        description: 'Cookie consent banner with accept and customize options.',
        kind: 'block',
        sidebarGroup: 'blocks-sections',
    },
    'copy-to-clipboard': {
        titleZh: '复制按钮',
        category: 'utility',
        dependencies: ['@lucide/vue'],
        description: 'Click-to-copy button with success feedback.',
    },
    counter: {
        titleZh: '数字滚动',
        category: 'data-display',
        dependencies: [],
        description: 'Animated number counter with formatting.',
    },
    'dashboard-shell': {
        titleZh: '仪表盘框架',
        category: 'marketing',
        dependencies: ['@lucide/vue'],
        description: 'Application shell layout with sidebar, header, and main content area.',
        kind: 'block',
        sidebarGroup: 'blocks-pages',
    },
    'data-table': {
        titleZh: '数据表格',
        category: 'data-display',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Full-featured data table with sorting, filtering, pagination, and row selection.',
    },
    'date-picker': {
        titleZh: '日期选择器',
        category: 'form',
        dependencies: ['v-calendar', '@lucide/vue', 'reka-ui'],
        description: 'Date picker with range selection, time input, and locale-aware formatting.',
        sidebarGroup: 'date-time',
    },
    descriptions: {
        titleZh: '描述列表',
        category: 'data-display',
        dependencies: [],
        description: 'Key-value description list in horizontal or vertical layout.',
    },
    dialog: {
        titleZh: '对话框',
        category: 'overlay',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Modal dialog with overlay, header, footer, and description.',
    },
    'dropdown-menu': {
        titleZh: '下拉菜单',
        category: 'overlay',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Dropdown menu with checkbox items, radio items, and sub-menus.',
    },
    'feedback-form': {
        titleZh: '反馈表单',
        category: 'marketing',
        dependencies: ['@lucide/vue'],
        description: 'User feedback form with rating and comment fields.',
        kind: 'block',
        sidebarGroup: 'blocks-sections',
    },
    'footer-section': {
        titleZh: '底部信息栏',
        category: 'marketing',
        dependencies: ['@lucide/vue'],
        description: 'Page footer with links, copyright, and social icons.',
        kind: 'block',
        sidebarGroup: 'blocks-sections',
    },
    form: {
        titleZh: '表单',
        category: 'form',
        dependencies: ['vee-validate', 'reka-ui'],
        description: 'Form validation and field management powered by vee-validate with wizard support.',
    },
    'glitch-text': {
        titleZh: '故障文本',
        category: 'visual-effect',
        dependencies: [],
        description: 'Text with glitch animation and distortion effects.',
    },
    'hardcore-input': {
        titleZh: '硬核输入框',
        category: 'form',
        dependencies: [],
        description: 'Input field with audio feedback and visual effects.',
    },
    'header-section': {
        titleZh: '顶部导航',
        category: 'marketing',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Page header with navigation, title, and subtitle.',
        kind: 'block',
        sidebarGroup: 'blocks-sections',
    },
    image: {
        titleZh: '图片',
        category: 'data-display',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Image component with lazy loading, fallback image, and Neo-Brutalist interactive preview modal.',
    },
    'infinite-scroll': {
        titleZh: '无限滚动',
        category: 'utility',
        dependencies: [],
        description: 'Auto-loading list that fetches more content on scroll.',
    },
    input: {
        titleZh: '输入框',
        category: 'form',
        dependencies: ['@lucide/vue'],
        description: 'Text input field with validation styling.',
    },
    kanban: {
        titleZh: '看板',
        category: 'utility',
        dependencies: ['@lucide/vue'],
        description: 'Drag-and-drop kanban board with columns and cards.',
        sidebarGroup: 'utility',
        docsSlug: 'kanban-board',
    },
    kbd: {
        titleZh: '键盘按键',
        category: 'utility',
        dependencies: [],
        description: 'Keyboard shortcut key display element.',
    },
    label: {
        titleZh: '标签',
        category: 'form',
        dependencies: ['reka-ui'],
        description: 'Form label associated with input controls.',
    },
    loading: {
        titleZh: '加载',
        category: 'feedback',
        dependencies: [],
        description: 'Container wrapper and v-loading custom directive for displaying loading state overlay with custom text.',
    },
    marquee: {
        titleZh: '跑马灯',
        category: 'visual-effect',
        dependencies: [],
        description: 'Auto-scrolling marquee banner for announcements.',
    },
    menu: {
        titleZh: '导航菜单',
        category: 'navigation',
        dependencies: ['@lucide/vue'],
        description: 'Horizontal or vertical navigation menu with sub-menu support.',
    },
    message: {
        titleZh: '消息提示',
        category: 'feedback',
        dependencies: ['@lucide/vue'],
        description: 'Imperative message notification system with singleton container, TransitionGroup stacking, and auto GC.',
    },
    'noise-background': {
        titleZh: '噪点背景',
        category: 'visual-effect',
        dependencies: [],
        description: 'Animated noise texture background overlay.',
    },
    'number-input': {
        titleZh: '数字输入框',
        category: 'form',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Numeric input with increment, decrement, and step controls.',
    },
    pagination: {
        titleZh: '分页',
        category: 'navigation',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Page navigation with first, previous, next, last controls and locale support.',
    },
    popconfirm: {
        titleZh: '气泡确认框',
        category: 'overlay',
        dependencies: ['@lucide/vue'],
        description: 'Confirmation popover with customizable content and actions.',
    },
    popover: {
        titleZh: '弹出层',
        category: 'overlay',
        dependencies: ['reka-ui'],
        description: 'Floating popover anchored to trigger elements.',
    },
    'pricing-section': {
        titleZh: '定价区',
        category: 'marketing',
        dependencies: ['@lucide/vue'],
        description: 'Pricing table with plan comparison and feature highlights.',
        kind: 'block',
        sidebarGroup: 'blocks-sections',
    },
    progress: {
        titleZh: '进度条',
        category: 'feedback',
        dependencies: ['reka-ui'],
        description: 'Determinate progress bar indicator.',
    },
    'radio-group': {
        titleZh: '单选组',
        category: 'form',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Mutually exclusive radio button group.',
    },
    rate: {
        titleZh: '评分',
        category: 'form',
        dependencies: ['@lucide/vue'],
        description: 'Star rating input with half-star precision and keyboard navigation.',
    },
    result: {
        titleZh: '结果',
        category: 'feedback',
        dependencies: ['@lucide/vue'],
        description: 'Feedback result display with state color blocks and action buttons.',
    },
    'scratch-card': {
        titleZh: '刮刮卡',
        category: 'visual-effect',
        dependencies: [],
        description: 'Scratch-off reveal card with canvas interaction.',
    },
    'scroll-area': {
        titleZh: '滚动区域',
        category: 'layout',
        dependencies: ['reka-ui'],
        description: 'Custom scrollable container with styled scrollbars.',
    },
    select: {
        titleZh: '选择器',
        category: 'form',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Single-value select dropdown with grouped items.',
    },
    separator: {
        titleZh: '分隔线',
        category: 'layout',
        dependencies: ['reka-ui'],
        description: 'Visual divider line between content sections.',
    },
    sheet: {
        titleZh: '抽屉',
        category: 'overlay',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Side panel overlay sliding from any edge of the viewport.',
    },
    skeleton: {
        titleZh: '骨架屏',
        category: 'feedback',
        dependencies: [],
        description: 'Loading placeholder skeletons for text, cards, avatars, and tables.',
    },
    'sketchy-chart': {
        titleZh: '手绘图表',
        category: 'data-display',
        dependencies: [],
        description: 'Hand-drawn style data visualization chart.',
    },
    slider: {
        titleZh: '滑块',
        category: 'form',
        dependencies: ['reka-ui'],
        description: 'Range slider with single or dual thumbs.',
    },
    spinner: {
        titleZh: '加载指示器',
        category: 'feedback',
        dependencies: [],
        description: 'Loading spinners with bars, blocks, and dots animation variants.',
    },
    stepper: {
        titleZh: '步骤条',
        category: 'navigation',
        dependencies: ['@lucide/vue'],
        description: 'Multi-step wizard with progress indicator.',
    },
    switch: {
        titleZh: '开关',
        category: 'form',
        dependencies: ['reka-ui'],
        description: 'Toggle switch for boolean on/off states.',
    },
    table: {
        titleZh: '表格',
        category: 'data-display',
        dependencies: [],
        description: 'Structured data table with header, body, footer, and caption.',
    },
    tabs: {
        titleZh: '标签页',
        category: 'navigation',
        dependencies: ['reka-ui'],
        description: 'Tabbed interface with content panels and locale support.',
    },
    'tags-input': {
        titleZh: '标签输入',
        category: 'form',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Input field for adding and removing tag chips.',
    },
    textarea: {
        titleZh: '文本域',
        category: 'form',
        dependencies: [],
        description: 'Multi-line text input with validation styling.',
    },
    timeline: {
        titleZh: '时间线',
        category: 'data-display',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Vertical timeline with connected events and content.',
    },
    toast: {
        titleZh: '轻提示',
        category: 'feedback',
        dependencies: ['@lucide/vue'],
        description: 'Ephemeral notification toasts with auto-dismiss and action support.',
    },
    toggle: {
        titleZh: '切换',
        category: 'action',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Pressable toggle button with active state.',
    },
    'toggle-group': {
        titleZh: '切换组',
        category: 'action',
        dependencies: ['reka-ui'],
        description: 'Group of toggle buttons with single or multiple selection.',
    },
    tooltip: {
        titleZh: '工具提示',
        category: 'overlay',
        dependencies: ['reka-ui'],
        description: 'Contextual tooltip triggered on hover or focus.',
    },
    tour: {
        titleZh: '导览',
        category: 'overlay',
        dependencies: [],
        description: 'Neo-Brutalist step-by-step interactive onboarding tour component with Canvas mask highlight.',
    },
    transfer: {
        titleZh: '穿梭框',
        category: 'form',
        dependencies: ['@lucide/vue'],
        description: 'Dual-panel transfer list for moving items between source and target collections.',
    },
    'tree-select': {
        titleZh: '树形选择器',
        category: 'form',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Hierarchical tree-based select with multi-select support.',
    },
    'tree-view': {
        titleZh: '树形目录',
        category: 'data-display',
        dependencies: ['reka-ui', '@lucide/vue'],
        description: 'Hierarchical tree with expandable nodes and selection.',
    },
    'typewriter-text': {
        titleZh: '打字机文本',
        category: 'visual-effect',
        dependencies: [],
        description: 'Text with typewriter typing animation effect.',
    },
    upload: {
        titleZh: '上传',
        category: 'form',
        dependencies: ['@lucide/vue'],
        description: 'File upload with drag-and-drop, preview, and progress tracking.',
    },
    'virtual-scroll': {
        titleZh: '虚拟滚动',
        category: 'utility',
        dependencies: ['@tanstack/vue-virtual'],
        description: 'High-performance virtualized list for large datasets.',
    },
    watermark: {
        titleZh: '水印',
        category: 'utility',
        dependencies: [],
        description: 'Watermark overlay with Canvas text/image rendering and MutationObserver anti-tampering.',
    },
};
