/**
 * Shared logic for generating `index.ts` barrel file content.
 *
 * Used by:
 *   - packages/ui/scripts/generate-component-index.ts (writes to disk during prebuild)
 *   - packages/registry/scripts/build-registry.ts (generates content inline for registry JSON)
 *
 * The `index.ts` barrel is a derived artifact — its content is fully determined
 * by the list of source files in the component directory. It is gitignored and
 * must NOT be scanned by scan-component-files.ts (which would create a circular
 * dependency: scanner picks up index.ts → manifest includes it → registry build
 * tries to read it from disk → fails on clean checkout where it hasn't been
 * generated yet).
 */

const AUTO_GEN_HEADER = `/**
 * AUTO-GENERATED by prebuild — DO NOT EDIT.
 * To add public exports, edit the underlying .vue/.ts file (it will be
 * picked up automatically on the next prebuild).
 */
`;

const TEST_FILE_PATTERN = /\.(test|spec)\.(ts|js|tsx|jsx)$/;
const SKIP_FILES = new Set(['index.ts']);

function vueFileNameToExportName(fileName: string): string {
    // kebab-case / snake_case / 空白 / 点分隔 → PascalCase，保证导出名是合法 JS 标识符，
    // 例如 my-button.vue → MyButton、foo.bar.vue → FooBar。
    // 对以数字开头的导出名（如 3d-card.vue → 3dCard）加 _ 前缀，避免非法标识符。
    return fileName
        .replace(/\.vue$/, '')
        .split(/[-_\s.]+/)
        .filter(Boolean)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('')
        .replace(/^\d/, '_$&');
}

function tsFileNameToModuleSpec(fileName: string): string {
    return `./${fileName.replace(/\.ts$/, '')}`;
}

/**
 * Generate the `index.ts` barrel file content from a list of component file names.
 *
 * Pattern:
 *   - `.vue` files → `export { default as PascalCase } from './File.vue'` + `export type *`
 *   - `.ts` files  → `export * from './file'`
 *   - `.css` files → skipped (side-effect imports handled by vite)
 *   - `index.ts`   → skipped (the file being generated)
 *   - test files   → skipped
 *
 * @param files - List of file names in the component directory (e.g. ['Accordion.vue', 'accordion-variants.ts'])
 * @returns The full `index.ts` file content as a string.
 */
export function buildComponentIndexContent(files: string[]): string {
    const lines: string[] = [AUTO_GEN_HEADER];

    const sortedFiles = [...files].sort();
    // 同名 `.vue` 与 `.ts` 会产生重叠导出（Button.vue → export { default as Button }，
    // Button.ts → export *，其具名导出可能与 Button 重名造成 TS2308）。
    // 检测键按 PascalCase 归一化（与 vueFileNameToExportName 的导出标识符对齐），
    // 使 button.vue 与 Button.ts 这类大小写变体冲突也能命中；.ts 侧具名导出按
    // 命名约定即为 PascalCase 文件名，该启发式偏保守（宁多告警不漏报）
    const seenExportKeys = new Set<string>();

    for (const file of sortedFiles) {
        if (SKIP_FILES.has(file)) continue;
        if (TEST_FILE_PATTERN.test(file)) continue;

        if (file.endsWith('.vue') || file.endsWith('.ts')) {
            const exportKey = vueFileNameToExportName(file.replace(/\.(vue|ts)$/, ''));
            if (seenExportKeys.has(exportKey)) {
                console.warn(`[buildComponentIndexContent] Ambiguous exports: "${file}" conflicts with another file exporting "${exportKey}". Rename one of them to avoid duplicate or overlapping exports.`);
            }
            seenExportKeys.add(exportKey);
        }

        if (file.endsWith('.vue')) {
            const exportName = vueFileNameToExportName(file);
            lines.push(`export { default as ${exportName} } from './${file}'`);
            lines.push(`export type * from './${file}'`);
        } else if (file.endsWith('.ts')) {
            lines.push(`export * from '${tsFileNameToModuleSpec(file)}'`);
        } else if (file.endsWith('.css')) {
            // 有意跳过：副作用导入由 vite 处理
        } else {
            console.warn(`[buildComponentIndexContent] Skipping unrecognized file: ${file}`);
        }
    }

    return lines.join('\n') + '\n';
}
