import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const cliRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(cliRoot, '../..');

console.log('[smoke-package] Verifying CLI package delivery contract...');

// 1. Ensure dist build exists
const distIndex = path.join(cliRoot, 'dist', 'index.js');
const distApi = path.join(cliRoot, 'dist', 'api.js');
const distDts = path.join(cliRoot, 'dist', 'api.d.ts');

for (const p of [distIndex, distApi, distDts]) {
    if (!fs.existsSync(p)) {
        throw new Error(`Required build artifact missing: ${p}. Run build first.`);
    }
}

const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'brutx-smoke-'));

try {
    console.log(`[smoke-package] Temporary isolated workspace: ${tmpRoot}`);

    // 2. Pack tarball
    console.log('[smoke-package] Running pnpm pack...');
    execSync('pnpm --config.ignore-scripts=true pack --pack-destination "' + tmpRoot + '"', {
        cwd: cliRoot,
        stdio: 'pipe',
        env: {
            ...process.env,
            npm_config_ignore_scripts: 'true',
        },
    });

    const tarballFiles = fs.readdirSync(tmpRoot).filter(f => f.endsWith('.tgz'));
    if (tarballFiles.length === 0) {
        throw new Error('No .tgz tarball was generated by pnpm pack');
    }
    const tarballPath = path.join(tmpRoot, tarballFiles[0]);
    console.log(`[smoke-package] Packed tarball: ${tarballFiles[0]}`);

    // 3. Extract tarball
    const extractedDir = path.join(tmpRoot, 'extracted');
    fs.mkdirSync(extractedDir, { recursive: true });
    execSync(`tar -xzf "${tarballPath}" -C "${extractedDir}"`, { stdio: 'pipe' });

    const packageRoot = path.join(extractedDir, 'package');
    if (!fs.existsSync(packageRoot)) {
        throw new Error('Expected extracted directory "package" was not found');
    }

    // 4. Audit package files for private dependencies
    console.log('[smoke-package] Auditing unpacked contents for private dependencies...');
    const privatePkg = 'brutx-shared-vue';

    function walkDir(dir) {
        const entries = fs.readdirSync(dir, { withFileTypes: true });
        for (const entry of entries) {
            const fullPath = path.join(dir, entry.name);
            if (entry.isDirectory()) {
                walkDir(fullPath);
            } else if (entry.isFile()) {
                if (entry.name.endsWith('.map')) {
                    continue;
                }
                if (entry.name === 'package.json') {
                    const pkg = JSON.parse(fs.readFileSync(fullPath, 'utf-8'));
                    const prodDeps = {
                        ...pkg.dependencies,
                        ...pkg.peerDependencies,
                        ...pkg.optionalDependencies,
                    };
                    if (privatePkg in prodDeps) {
                        throw new Error(`Tarball leak detected: package.json production dependencies contain "${privatePkg}"`);
                    }
                    continue;
                }
                const content = fs.readFileSync(fullPath, 'utf-8');
                if (content.includes(privatePkg)) {
                    throw new Error(`Tarball leak detected: "${fullPath}" contains reference to "${privatePkg}"`);
                }
            }
        }
    }
    walkDir(packageRoot);
    console.log('[smoke-package] Tarball file audit passed: 0 internal references found.');

    // 5. Setup isolated consumer
    const consumerDir = path.join(tmpRoot, 'consumer');
    fs.mkdirSync(consumerDir, { recursive: true });
    fs.writeFileSync(
        path.join(consumerDir, 'package.json'),
        JSON.stringify({ name: 'smoke-consumer', type: 'module', private: true }, null, 2),
    );

    console.log('[smoke-package] Installing packed tarball and @types/node in isolated consumer...');
    execSync(`pnpm add "${tarballPath}" @types/node`, {
        cwd: consumerDir,
        stdio: 'inherit',
        env: {
            ...process.env,
            NODE_PATH: '',
        },
    });

    // 6. Test CLI execution from installed package
    console.log('[smoke-package] Testing CLI executable output from installed package...');
    const helpOutput = execSync('pnpm exec brutx-vue --help', {
        cwd: consumerDir,
        encoding: 'utf-8',
        env: {
            ...process.env,
            NODE_PATH: '',
        },
    });
    if (!helpOutput.includes('brutx-vue') && !helpOutput.includes('Usage:')) {
        throw new Error(`CLI help output unexpected: ${helpOutput}`);
    }
    console.log('[smoke-package] CLI execution passed.');

    // 7. Test runtime dynamic import in consumer
    console.log('[smoke-package] Testing consumer runtime import...');
    const runtimeTestScript = `
        import { RegistryClient, isComponentNotFoundError, isRegistrySecurityError, REGISTRY_ERROR_CODES } from 'brutx-vue';
        import { RegistryClient as ApiClient } from 'brutx-vue/api';
        if (typeof RegistryClient !== 'function' || typeof ApiClient !== 'function') {
            throw new Error('RegistryClient is not a function');
        }
        if (typeof isComponentNotFoundError !== 'function') {
            throw new Error('isComponentNotFoundError is not a function');
        }
        if (typeof isRegistrySecurityError !== 'function') {
            throw new Error('isRegistrySecurityError is not a function');
        }
        if (!Array.isArray(REGISTRY_ERROR_CODES) || !REGISTRY_ERROR_CODES.includes('COMPONENT_NOT_FOUND')) {
            throw new Error('REGISTRY_ERROR_CODES is missing or invalid');
        }
        console.log('Runtime import verification succeeded.');
    `;
    const runtimeScriptPath = path.join(consumerDir, 'test-runtime.mjs');
    fs.writeFileSync(runtimeScriptPath, runtimeTestScript, 'utf-8');
    execSync(`node "${runtimeScriptPath}"`, {
        cwd: consumerDir,
        stdio: 'inherit',
        env: {
            ...process.env,
            NODE_PATH: '',
        },
    });

    // 8. Test TypeScript NodeNext consumption
    console.log('[smoke-package] Testing TypeScript NodeNext mode (strict: true, skipLibCheck: false)...');
    const consumerFixturePath = path.join(cliRoot, 'test-d', 'consumer', 'consumer-test.ts');
    const consumerTestSrc = fs.readFileSync(consumerFixturePath, 'utf-8');
    fs.writeFileSync(path.join(consumerDir, 'test-nodenext.ts'), consumerTestSrc, 'utf-8');

    fs.writeFileSync(
        path.join(consumerDir, 'tsconfig.nodenext.json'),
        JSON.stringify(
            {
                compilerOptions: {
                    target: 'ES2022',
                    module: 'NodeNext',
                    moduleResolution: 'NodeNext',
                    strict: true,
                    skipLibCheck: false,
                    noEmit: true,
                },
                include: ['test-nodenext.ts'],
            },
            null,
            2,
        ),
    );

    execSync(`pnpm exec tsc --project "${path.join(consumerDir, 'tsconfig.nodenext.json')}"`, {
        cwd: repoRoot,
        stdio: 'inherit',
        env: {
            ...process.env,
            NODE_PATH: '',
        },
    });
    console.log('[smoke-package] TypeScript NodeNext mode passed.');

    // 9. Test TypeScript Bundler consumption
    console.log('[smoke-package] Testing TypeScript Bundler mode (strict: true, skipLibCheck: false)...');
    fs.writeFileSync(path.join(consumerDir, 'test-bundler.ts'), consumerTestSrc, 'utf-8');

    fs.writeFileSync(
        path.join(consumerDir, 'tsconfig.bundler.json'),
        JSON.stringify(
            {
                compilerOptions: {
                    target: 'ES2022',
                    module: 'ESNext',
                    moduleResolution: 'Bundler',
                    strict: true,
                    skipLibCheck: false,
                    noEmit: true,
                },
                include: ['test-bundler.ts'],
            },
            null,
            2,
        ),
    );

    execSync(`pnpm exec tsc --project "${path.join(consumerDir, 'tsconfig.bundler.json')}"`, {
        cwd: repoRoot,
        stdio: 'inherit',
        env: {
            ...process.env,
            NODE_PATH: '',
        },
    });
    console.log('[smoke-package] TypeScript Bundler mode passed.');

    console.log('[smoke-package] ALL CHECKS PASSED: Package is 100% self-contained and clean.');
} finally {
    try {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    } catch {
        // ignore cleanup error
    }
}
