export interface ComponentFileMapping {
    files: string[];
    composables?: string[];
    locales?: string[];
}

export const COMPONENT_FILES: Record<string, ComponentFileMapping> = {
    alert: { files: ['Alert.vue', 'AlertDescription.vue', 'AlertTitle.vue', 'alert-variants.ts'] },
    avatar: { files: ['Avatar.vue', 'AvatarFallback.vue', 'AvatarImage.vue', 'avatar-variants.ts', 'avatar-key.ts'] },
    badge: { files: ['Badge.vue', 'badge-variants.ts'] },
    button: { files: ['Button.vue', 'button-variants.ts'] },
    calendar: { files: ['Calendar.vue'] },
    card: { files: ['Card.vue', 'CardContent.vue', 'CardDescription.vue', 'CardFooter.vue', 'CardHeader.vue', 'CardTitle.vue', 'card-variants.ts'] },
    checkbox: { files: ['Checkbox.vue', 'checkbox-variants.ts'] },
    combobox: { files: ['Combobox.vue', 'ComboboxMulti.vue', 'combobox-types.ts'], composables: ['useLocale.ts'] },
    command: { files: ['Command.vue', 'CommandDialog.vue', 'CommandEmpty.vue', 'CommandGroup.vue', 'CommandInput.vue', 'CommandItem.vue', 'CommandList.vue', 'CommandSeparator.vue', 'CommandShortcut.vue', 'command-context.ts', 'command-variants.ts'], composables: ['useLocale.ts'] },
    dialog: { files: ['DialogContent.vue', 'DialogDescription.vue', 'DialogFooter.vue', 'DialogHeader.vue', 'DialogOverlay.vue', 'DialogTitle.vue', 'dialog-variants.ts'], composables: ['useLocale.ts'] },
    'dropdown-menu': { files: ['DropdownMenuCheckboxItem.vue', 'DropdownMenuContent.vue', 'DropdownMenuItem.vue', 'DropdownMenuLabel.vue', 'DropdownMenuRadioItem.vue', 'DropdownMenuSeparator.vue', 'DropdownMenuShortcut.vue', 'DropdownMenuSubContent.vue', 'DropdownMenuSubTrigger.vue', 'dropdown-menu-variants.ts'] },
    input: { files: ['Input.vue', 'input-variants.ts'] },
    label: { files: ['Label.vue', 'label-variants.ts'] },
    pagination: { files: ['Pagination.vue', 'pagination-variants.ts'], composables: ['useLocale.ts'] },
    popover: { files: ['PopoverContent.vue', 'popover-variants.ts'] },
    'scroll-area': { files: ['ScrollArea.vue', 'ScrollBar.vue', 'scroll-area-variants.ts'] },
    select: { files: ['SelectContent.vue', 'SelectItem.vue', 'SelectLabel.vue', 'SelectScrollDownButton.vue', 'SelectScrollUpButton.vue', 'SelectSeparator.vue', 'SelectTrigger.vue', 'select-variants.ts'] },
    separator: { files: ['Separator.vue', 'separator-variants.ts'] },
    skeleton: { files: ['Skeleton.vue', 'SkeletonAvatar.vue', 'SkeletonCard.vue', 'SkeletonTable.vue', 'SkeletonText.vue', 'skeleton-variants.ts'] },
    spinner: { files: ['Spinner.vue', 'BarsSpinner.vue', 'BlockSpinner.vue', 'DotsSpinner.vue', 'spinner-variants.ts'], composables: ['useLocale.ts'] },
    'submit-button': { files: ['SubmitButton.vue'], composables: ['useLocale.ts'] },
    switch: { files: ['Switch.vue', 'switch-variants.ts'] },
    table: { files: ['Table.vue', 'TableBody.vue', 'TableCaption.vue', 'TableCell.vue', 'TableFooter.vue', 'TableHead.vue', 'TableHeader.vue', 'TableRow.vue', 'table-variants.ts'] },
    tabs: { files: ['TabsContent.vue', 'TabsList.vue', 'TabsTrigger.vue', 'tabs-variants.ts'] },
    textarea: { files: ['Textarea.vue', 'textarea-variants.ts'], composables: ['useLocale.ts'] },
    toast: { files: ['Toast.vue', 'ToastContainer.vue', 'toast-variants.ts'], composables: ['useToast.ts', 'useLocale.ts'] },
    tooltip: { files: ['TooltipContent.vue', 'tooltip-variants.ts'] },
    'saas-pricing': { files: ['SaaSPricing.vue'], composables: ['useLocale.ts'] },
    'dashboard-stats': { files: ['DashboardStats.vue'], composables: ['useLocale.ts'] },
    form: { files: ['Form.vue', 'FormControl.vue', 'FormDescription.vue', 'FormField.vue', 'FormItem.vue', 'FormLabel.vue', 'FormMessage.vue', 'form-context.ts', 'FormWizard.vue', 'form-wizard-types.ts', 'form-wizard-variants.ts'] },
    'alert-dialog': { files: ['AlertDialogAction.vue', 'AlertDialogCancel.vue', 'AlertDialogContent.vue', 'AlertDialogDescription.vue', 'AlertDialogFooter.vue', 'AlertDialogHeader.vue', 'AlertDialogTitle.vue', 'alert-dialog-variants.ts'] },
    sheet: { files: ['SheetContent.vue', 'SheetDescription.vue', 'SheetFooter.vue', 'SheetHeader.vue', 'SheetTitle.vue', 'sheet-variants.ts'], composables: ['useLocale.ts'] },
    'radio-group': { files: ['RadioGroup.vue', 'RadioGroupItem.vue', 'radio-group-variants.ts'] },
    slider: { files: ['Slider.vue', 'slider-variants.ts'] },
    progress: { files: ['Progress.vue', 'progress-variants.ts'] },
    toggle: { files: ['Toggle.vue', 'toggle-variants.ts'] },
    'toggle-group': { files: ['ToggleGroup.vue', 'ToggleGroupItem.vue', 'toggle-group-key.ts'] },
    'brutalist-hero': { files: ['BrutalistHero.vue'], composables: ['useLocale.ts'] },
    'pricing-section': { files: ['PricingSection.vue'], composables: ['useLocale.ts'] },
    'auth-card': { files: ['AuthCard.vue'], composables: ['useLocale.ts'] },
    'dashboard-shell': { files: ['DashboardShell.vue'], composables: ['useLocale.ts'] },
    'empty-state': { files: ['EmptyState.vue'], composables: ['useLocale.ts'] },
    'waitlist-page': { files: ['WaitlistPage.vue'], composables: ['useLocale.ts'] },
    accordion: { files: ['Accordion.vue', 'AccordionItem.vue', 'AccordionTrigger.vue', 'AccordionContent.vue', 'accordion-key.ts', 'accordion-variants.ts'] },
    'tags-input': { files: ['TagsInput.vue', 'TagsInputInput.vue', 'TagsInputItem.vue', 'TagsInputItemText.vue', 'TagsInputItemDelete.vue', 'tags-input-variants.ts'] },
    'number-input': { files: ['NumberInput.vue', 'number-input-variants.ts'], composables: ['useLocale.ts'] },
    'copy-to-clipboard': { files: ['CopyToClipboard.vue', 'copy-to-clipboard-variants.ts'], composables: ['useClipboard.ts', 'useLocale.ts'] },
    breadcrumb: { files: ['Breadcrumb.vue', 'BreadcrumbList.vue', 'BreadcrumbItem.vue', 'BreadcrumbLink.vue', 'BreadcrumbPage.vue', 'BreadcrumbSeparator.vue', 'BreadcrumbEllipsis.vue', 'breadcrumb-variants.ts'], composables: ['useLocale.ts'] },
    marquee: { files: ['Marquee.vue', 'marquee-variants.ts'] },
    'before-after': { files: ['BeforeAfter.vue', 'before-after-variants.ts'], composables: ['useLocale.ts'] },
    'code-block': { files: ['CodeBlock.vue', 'prism-languages.ts', 'brutx-prism.css', 'code-block-variants.ts'], composables: ['useLocale.ts'] },
    timeline: { files: ['Timeline.vue', 'TimelineItem.vue', 'TimelineSeparator.vue', 'TimelineDot.vue', 'TimelineConnector.vue', 'TimelineContent.vue', 'timeline-key.ts', 'timeline-variants.ts'] },
    carousel: { files: ['Carousel.vue', 'CarouselItem.vue', 'carousel-variants.ts'], composables: ['useLocale.ts'] },
    'tree-view': { files: ['TreeView.vue', 'TreeViewNode.vue', 'tree-view-variants.ts'], composables: ['useLocale.ts'] },
    kanban: { files: ['KanbanBoard.vue', 'kanban-variants.ts'], composables: ['useLocale.ts'] },
    'chat-bubble': { files: ['ChatBubble.vue', 'chat-bubble-variants.ts'] },
    kbd: { files: ['Kbd.vue', 'kbd-variants.ts'] },
    counter: { files: ['Counter.vue', 'counter-variants.ts'] },
    stepper: { files: ['Stepper.vue', 'stepper-variants.ts'], composables: ['useLocale.ts'] },
    'card-3d': { files: ['Card3D.vue', 'card-3d-variants.ts'], composables: ['useReducedMotion.ts', 'useLocale.ts'] },
    'glitch-text': { files: ['GlitchText.vue', 'glitch-text-variants.ts'], composables: ['useReducedMotion.ts'] },
    'scratch-card': { files: ['ScratchCard.vue', 'scratch-card-variants.ts'], composables: ['useReducedMotion.ts', 'useCanvasInteraction.ts', 'useLocale.ts'] },
    'sketchy-chart': { files: ['SketchyChart.vue', 'sketchy-chart-variants.ts'], composables: ['useLocale.ts'] },
    'hardcore-input': { files: ['HardcoreInput.vue', 'hardcore-input-variants.ts'], composables: ['useAudioEngine.ts', 'useLocale.ts'] },
    'testimonial-card': { files: ['TestimonialCard.vue'], composables: ['useLocale.ts'] },
    'blog-card': { files: ['BlogCard.vue'], composables: ['useLocale.ts'] },
    'file-card': { files: ['FileCard.vue'], composables: ['useLocale.ts'] },
    'quick-actions': { files: ['QuickActions.vue'], composables: ['useLocale.ts'] },
    'faq-section': { files: ['FaqSection.vue'], composables: ['useLocale.ts'] },
    'tabs-nav': { files: ['TabsNav.vue'], composables: ['useLocale.ts'] },
    'header-section': { files: ['HeaderSection.vue'], composables: ['useLocale.ts'] },
    'footer-section': { files: ['FooterSection.vue'], composables: ['useLocale.ts'] },
    'not-found-page': { files: ['NotFoundPage.vue'], composables: ['useLocale.ts'] },
    'loading-page': { files: ['LoadingPage.vue'], composables: ['useLocale.ts'] },
    'error-card': { files: ['ErrorCard.vue'], composables: ['useLocale.ts'] },
    'success-card': { files: ['SuccessCard.vue'], composables: ['useLocale.ts'] },
    'search-widget': { files: ['SearchWidget.vue'], composables: ['useLocale.ts'] },
    'feedback-form': { files: ['FeedbackForm.vue'], composables: ['useLocale.ts'] },
    'stepper-section': { files: ['StepperSection.vue'], composables: ['useLocale.ts'] },
    'cookie-consent': { files: ['CookieConsent.vue'], composables: ['useLocale.ts'] },
    'data-table-section': { files: ['DataTableSection.vue', 'types.ts'], composables: ['useLocale.ts'] },
    'settings-page': { files: ['SettingsPage.vue'], composables: ['useLocale.ts'] },
    'blog-list-page': { files: ['BlogListPage.vue'], composables: ['useLocale.ts'] },
    'activity-log-page': { files: ['ActivityLogPage.vue'], composables: ['useLocale.ts'] },
    'profile-page': { files: ['ProfilePage.vue'], composables: ['useLocale.ts'] },
    'chart-section': { files: ['ChartSection.vue'], composables: ['useLocale.ts'] },
    'gallery-section': { files: ['GallerySection.vue'], composables: ['useLocale.ts'] },
    'upload-card': { files: ['UploadCard.vue'], composables: ['useLocale.ts'] },
    'overview-page': { files: ['OverviewPage.vue'], composables: ['useLocale.ts'] },
    'color-picker': {
        files: ['ColorPicker.vue', 'ColorPickerPanel.vue', 'ColorPickerSwatch.vue', 'ColorPickerInput.vue', 'ColorPickerHistory.vue', 'color-picker-variants.ts', 'types.ts'],
        composables: ['useLocale.ts', 'useColorHistory.ts'],
    },
    'date-picker': {
        files: [
            'DatePicker.vue',
            'DatePickerPanel.vue',
            'DatePickerRange.vue',
            'DatePickerRangePanel.vue',
            'TimePicker.vue',
            'DateTimePicker.vue',
            'DateTimePickerPanel.vue',
            'WeekPicker.vue',
            'WeekPickerPanel.vue',
            'MonthPicker.vue',
            'MonthPickerPanel.vue',
            'YearPicker.vue',
            'YearPickerPanel.vue',
            'date-picker-variants.ts',
            'types.ts',
            'panel-styles.css',
        ],
        composables: ['useLocale.ts'],
    },
    'color-mode-switcher': {
        files: ['ColorModeSwitcher.vue'],
        composables: ['useTheme.ts'],
    },
    'data-table': {
        files: ['DataTable.vue', 'data-table-variants.ts', 'types.ts'],
        composables: ['useLocale.ts', 'useDataTableSort.ts', 'useDataTableFilter.ts', 'useDataTableSelection.ts', 'useDataTablePagination.ts'],
    },
    'tree-select': {
        files: ['TreeSelect.vue', 'TreeSelectNode.vue', 'tree-select-variants.ts', 'tree-select-types.ts'],
        composables: ['useLocale.ts'],
    },
    'typewriter-text': {
        files: ['TypewriterText.vue', 'typewriter-text-variants.ts'],
        composables: ['useReducedMotion.ts'],
    },
    'noise-background': {
        files: ['NoiseBackground.vue', 'noise-background-variants.ts'],
    },
    'glitch-button': {
        files: ['GlitchButton.vue', 'glitch-button-variants.ts'],
        composables: ['useReducedMotion.ts'],
    },
    'virtual-scroll': {
        files: ['VirtualScroll.vue', 'virtual-scroll-variants.ts', 'types.ts'],
        composables: ['useLocale.ts'],
    },
};
